### ISSUE TITLE
Does it support Engelmann WaserStar M?

### ISSUE THREAD

**Issue by okainov** [wmbusmeters/wmbusmeters#1001]
### Type of request

New device support

### Meter description

I don't see any information in the repo about Engelmann WaserStar M support. Is it supported?

Screenshot from the manual:
![image](https://github.com/merbanan/rtl_433/assets/918446/22a37fd3-556d-4efa-bc3f-f817cd00eb1b)

Manual https://www.engelmann.de/wp-content/uploads/2023/03/1081600001_2022-12-22_BA_WaterStar_M_MID_de_en.pdf
Some docs on official website https://www.engelmann.de/en/applications/water-meter-in-practice/

I have the receiver and the water meter with the radio function activated, but I don't know how can I figure out the signals/decode them. 

### Logged telegrams from meter in decrypted format

```shell
Don't have any...
```

**Comment by BIBOLV** [comment]
Try to capture few telegrams and then it will be possible to see if values are being recognized.
