### ISSUE TITLE
Desired link modes none cannot be set for device 00000001:rtl433[00000001]

### ISSUE THREAD

**Issue by LukaszP2** [wmbusmeters/wmbusmeters#1061]
### Type of request

Bug

### HAOS version

2023.10.3

### wmbusmeters version

1.14.0

### Your message goes here

I change wmbusmeters  version from (I think 1.11 - from old repository) to 1.14 and copy my old config to new one. Now its doesn't work...
```
Started config rtl433[00000001] listening on none using fq 868.95M
Warning! Desired link modes none cannot be set for device 00000001:rtl433[00000001]
```
My config from old one:
```
  loglevel=normal
  device=rtl433:868.95M
  donotprobe=/dev/ttyAMA0
  logtelegrams=false
  format=json
  logfile=/dev/stdout
  shell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
    driver=unismart
```
and new one:
![image](https://github.com/wmbusmeters/wmbusmeters/assets/44735995/92918058-5e24-4a3e-a1ee-39bc9e4431e5)

**Comment by BIBOLV** [comment]
RTL-SDR devices has issues with latest ha-addon version - https://github.com/wmbusmeters/wmbusmeters/issues/989
