### ISSUE TITLE
Installation on Raspberry PI OS

### ISSUE THREAD

**Issue by Flearz** [wmbusmeters/wmbusmeters#1073]
### Type of request

Question

### OS version

Raspberry PI OS (Debian)

### wmbusmeters version

Latest

### Your message goes here

Hello,
I am sorry to bother you with this stupid request.
I am currently doing a master thesis that involves the capture of wireless M-Bus frames so I naturally ended up looking at your (awesome) project.

I have some troubles installating the package on my Raspberry PI, I never installed a project from git like this.
I cloned the project in a repository and tried doing "./configure; make; sudo make install"
When doing the "configure" i get "could not find rtsldr library, try apt install rtsldr".

Could you please tell me what I am doing wrong ? 

Sorry again and thanks in advance

Henri

**Comment by caribbeanyute** [comment]
I was able to run ./configure on my PI, after running ```sudo apt install librtlsdr-dev libxml2-dev```, 
then compiled using `make`. 
Take note, though, that if using an rtl-sdr you may also have to compile [https://github.com/xaelsouth/rtl-wmbus](url).

**Comment by Flearz** [comment]
It worked, thanks !!
