### ISSUE TITLE
src/driver_iwmtx5.cc is set to be HeatMeter though it's a WaterMeter

### ISSUE THREAD

**Issue by lindsand** [wmbusmeters/wmbusmeters#1075]
### Type of request

Existing device improvement

### Meter description

src/driver_iwmtx5.cc has
        di.setMeterType(MeterType::HeatMeter);

It's a water meter from BMETERS  so it should be
        di.setMeterType(MeterType::WaterMeter);

https://www.bmeters.com/en/products/iwm-tx5/

### Logged telegrams from meter in decrypted format

```shell
// Test: WaterWater iwmtx5 22917370 00000000000000000000000000000000
// telegram=|5144b4097073912218078c00247a0308400571e9615249ede52eaae09f61908f027c3877f3330ae9079528b23173ce124bcc255393e60b173c0a9f274c42dd92e4b23c14e8a41f042903358df01dd9268ad4|
// {"id": "22917370","media": "water","meter": "iwmtx5","meter_datetime": "2023-05-11 10:38:24","name": "WaterWater","status": "PERMANENT_ERROR","timestamp": "1111-11-11T11:11:11Z","total_m3": 0.025}
// |WaterWater;22917370;PERMANENT_ERROR;0.025;1111-11-11 11:11.11
```

**Comment by weetmuts** [comment]
Thanks!  It is now fixed.  https://github.com/wmbusmeters/wmbusmeters/commit/10fbac056b80afd4c7a4a368a5f5310b715c951f
