### ISSUE TITLE
Qalcosonic W1 support

### ISSUE THREAD

**Issue by rstephan** [wmbusmeters/wmbusmeters#1084]
### Type of request

Enhancement

### OS version

Ubuntu

### wmbusmeters version

master

### Your message goes here

We have a "Qalcosonic W1" water meter (without an **u**).

With 
```
di.addDetection(MANUFACTURER_AXI, 0x07,  0x01);
```
in `driver_q400.cc` it is working without any problems.

By the way, what is a q**u**alcosonic (with an **u**)?

**Comment by weetmuts** [comment]
Can you provide an example telegram here? I try to maintain in the source code a test database for all drivers and types of telegrams. Thanks!

**Comment by weetmuts** [comment]
> By the way, what is a qualcosonic (with an u)?

A spelling error? :-)

**Comment by rstephan** [comment]
Here is an example telegram:

```
434409072928420601078c200c900f002c250c000000a250838f8980c5517a0c00200710b83bde20a9fd07c5c81edb1f9a3843a16ec80938edf974e556ec9ad34b2ed06e
```
