### ISSUE TITLE
Source code from wmbusmeters.org telegram analyzer  ? 

### ISSUE THREAD

**Issue by sigmounte** [wmbusmeters/wmbusmeters#1092]
### Type of request

Enhancement

### OS version

debian 11

### wmbusmeters version

1

### Your message goes here

Is there a way to obtain the source code of the telegram analyzer on the / of wmbusmeters.org ??

Thanks

**Comment by weetmuts** [comment]
As the page says:
This service is identical to running locally: wmbusmeters --analyze=<driver>:<key> <hex> 

:-)
So, yeah, that is what it is doing. You can add :html after the <key> to get the colors as <span>...</span>
as well.

Do you want to help out improving it?
