### ISSUE TITLE
Munia driver below 0 temp interpretation

### ISSUE THREAD

**Issue by jacek27** [wmbusmeters/wmbusmeters#1103]
### Type of request

Bug

### OS version

Debian 12 / Docker

### wmbusmeters version

1.11.0-142-gc84c4d3

### Your message goes here

With temps below 0 munia driver interprets values as large numbers 

example 
![image](https://github.com/wmbusmeters/wmbusmeters/assets/9624103/728106e4-bb6c-4635-a8b8-3af4a1ad7bed)

when the temp outside is 0.6 below 0

**Comment by weetmuts** [comment]
I think this should be solved. This meter uses BCD and the new code will automatically detect negative BCD values.

**Comment by weetmuts** [comment]
Fixed. Closing.

**Comment by weetmuts** [comment]
https://github.com/wmbusmeters/wmbusmeters/issues/1238
