### ISSUE TITLE
smart meter Integra 

### ISSUE THREAD

**Issue by Fiorello8** [wmbusmeters/wmbusmeters#1105]
Explain the problem..... 

https://wmbusmeters.org/analyze/4244b4254346191010078c202e7a9900002004138a08000084101316000000043b00000000025ada00046d122cee2944138a080000426cff2802fd17800002fd741216:auto:00B23FD66308978DE19C6CE456E6ED45

Unfortunately the tool does not work

I am expecting the following values

Can you check the problem ?
thanks in advance

Volume: 0413; 8a080000 => 2186 Litres
Reverse volume: 841013; 16000000 => 22 lt
Flow rate:043b; 00000000 => 0 L/h
Water temp: 025a; da00 =>21.8°C
Instant date: 046d; 122cee29 => 14.9.2023 12:18
Target monthly volume: 4413; 8a080000 =>2186 Lt
Target date: 426c; ff28 => 31.8.2023
Error: 02fd17; 8000=> no consumption
Remaining battery lifetime: 02fd74; 1216 => 5650 days

**Comment by Andi252** [comment]
Hi, the telegram 4244b4254346191010078c202e7a9900002004138a08000084101316000000043b00000000025ada00046d122cee2944138a080000426cff2802fd17800002fd741216
is alread decrypted, try without your key and you will find exactly the values you expect.
