### ISSUE TITLE
can not make on alpine linux

### ISSUE THREAD

**Issue by rudiratlos** [wmbusmeters/wmbusmeters#1134]
### Type of request

Enhancement

### OS version

alpine linux

### wmbusmeters version

latest

### Your message goes here

on alpine linux, I can not compile wmbusmeters. following this howto:
[https://the78mole.de/wmbus-meters-and-how-to-get-it-into-home-assistant/](url)

multiple errors like this:
src/units.h:152:14: error: int8_t has not been declared

**Comment by BIBOLV** [comment]
There is no need to build manually - you can follow information [here](https://github.com/wmbusmeters/wmbusmeters-ha-addon).
