### ISSUE TITLE
Negative Flow Value in sensostar

### ISSUE THREAD

**Issue by ovettel** [wmbusmeters/wmbusmeters#1140]
It seems that the current sensostar driver does not interpret negative flow values correctly, but instead those get mapped somewhere close to 2^32. This may be an easy fix, I read something about AutoSigned, but I don't have time at the moment to look at it myself. Raising this issue in case someone else has time to take a look...

Here's a telegram that reports a negative flow value:

https://wmbusmeters.org/analyze/6044c5145573752300047ac70000202f2f046d1e2d0d310406f82a000001fd170004137acf1700043Be3ffffff042Bea090000025B2800025f3B00026168f884401300000000848040130000000084c040130000000003fd0c05000002fd0B1011 

Here's another where the value is positive:
https://wmbusmeters.org/analyze/6044C5145573752300047AC0000020_2F2F046D2D2B0D310406F42A000001FD1700041309CF1700043B21000000042BBA010000025B3F00025F34000261810484401300000000848040130000000084C040130000000003FD0C05000002FD0B1011

**Comment by weetmuts** [comment]
https://github.com/wmbusmeters/wmbusmeters/issues/1238
