### ISSUE TITLE
telegrams monthly

### ISSUE THREAD

**Issue by mauriziozito01** [wmbusmeters/wmbusmeters#1143]
### Type of request

Question

### OS version

raspbian

### wmbusmeters version

last

### Your message goes here

Hi everyone
I would like to ask you some information
I followed this project.

wmbusmeters hears nothing except 169Mhz telegrams in n mode.
It's probably the electricity meter.
I don't need this meter but I would like to read the water and gas meters.
These meters probably transmit at 430Mhz.
They probably only send a few .
So I would like to put wmbusmeters to listen to all telegrams transmitted at 430Mhz and send them to MQTT.
Then I write a python job that goes to MQTT and if it finds something it saves these telegrams somewhere, so I can easily check offline.
Is it possible to put wmbusmeters in this generic reading mode?
If so, can you tell me how?

Thanks in advance.

I apologize for my English which is probably not perfect.

Maurizio

**Comment by BIBOLV** [comment]
Hi,
Frequency and mode that is being listened to depends on receiver you have and how you configure it. I would suggest to review documentation and still you do not succeed with configuration then provide more details about your setup.
