### ISSUE TITLE
How to configure a Meter with 2 Totals

### ISSUE THREAD

**Issue by learnlinuxnow** [wmbusmeters/wmbusmeters#1162]
### Type of request

Question

### HAOS version

2024.1.5

### wmbusmeters version

1.14.0-101-1

### Your message goes here

How to select a single Value, cause my Meter (Qundis 5.5heat) ist transmitting a year total anders an all time total value.

At the Moment the value ist jumping between both values...

**Comment by weetmuts** [comment]
Can you post some --logtelegrams here?
