### ISSUE TITLE
Water meter data decryption

### ISSUE THREAD

**Issue by dongxiaojiedxj** [wmbusmeters/wmbusmeters#1170]
I obtained the message data of the water meter, which is encrypted by aes128 and CBC, but it cannot be parsed using the java function in utils. What is the problem? The following data and keys
Water meter message: 4E448F410064372035077A48004005326BA7F0D19A3E7A20D6F124285E61435300240EC8C32117D371178369FE502AD5F39EB1BCCD45921CBFE367494AFDAEF920 E85B7278697876C0D6D89FB0CB8A
key:776D627573656E63727970746B657931
In addition, I tested the website online and found that it can be parsed. How should I use it to correctly decrypt and obtain the information?
https://wmbusmeters.org/analyze/4E448F410064372035077A48004005326BA7F0D19A3E7A20D6F124285E61435300240EC8C32117D371178369FE502AD5F39EB1BCCD45921CBFE3674 94AFDAEF920E85B7278697876C0D6D89FB0CB8A:auto:776D627573656E63727970746B657931

**Comment by weetmuts** [comment]
The util is only for KEM files from Kamstrup not for the telegrams themselves. You can analyze like this:

./build/wmbusmeters --analyze=776D627573656E63727970746B657931 4E448F410064372035077A48004005326BA7F0D19A3E7A20D6F124285E61435300240EC8C32117D371178369FE502AD5F39EB1BCCD45921CBFE367494AFDAEF920E85B7278697876C0D6D89FB0CB8A

Or for decoding only:
./build/wmbusmeters --format=json 4E448F410064372035077A48004005326BA7F0D19A3E7A20D6F124285E61435300240EC8C32117D371178369FE502AD5F39EB1BCCD45921CBFE367494AFDAEF920E85B7278697876C0D6D89FB0CB8A Water evo868 20376400 776D627573656E63727970746B657931

Looks like a pretty standard meter. Do you have a company/product name and documentation (for the error flags) that we can use to add a new driver for this?

**Comment by Uzlopak** [comment]
776D627573656E63727970746B657931 is hexadecimal for wmbusencryptkey1

LOL
