### ISSUE TITLE
Multiple receiving devices

### ISSUE THREAD

**Issue by pascaltippelt** [wmbusmeters/wmbusmeters#1174]
### Type of request

Enhancement

### OS version

Debian 12

### wmbusmeters version

1.14

### Your message goes here

I am wondering if it would be possible to bind multiple devices. I have some devices sending in T1 / C1, which I can read using my amb8465. But 2 devices are still S1-Mode. Any chance setting up a second amb8465 device to listen to s1 exclusively?

Best Pascal

**Comment by BIBOLV** [comment]
Yes, it is also described on documentation - it is possible to use multiple devices, by setting multiple `device=` definitions.
