### ISSUE TITLE
wmbusmeters/wmbusmeters:release-1.15.0 missing in Docker Hub

### ISSUE THREAD

**Issue by ChristianHeinemann** [wmbusmeters/wmbusmeters#1183]
### Type of request

Bug

### OS version

linux/amd64

### wmbusmeters version

1.15.0

### Your message goes here

The Docker image tag was not created properly. There is a tag "[release-](https://hub.docker.com/layers/wmbusmeters/wmbusmeters/release-/images/sha256-b5b426d585097e55f664c34c4ecc06c32df9cb3d1cfb3d6f8eca626bfee5b892?context=explore)" (without the version suffix) created in [pipeline run](https://github.com/wmbusmeters/wmbusmeters/actions/runs/7905568384) for the [1.15.0](https://github.com/wmbusmeters/wmbusmeters/releases/tag/1.15.0) release, but "release-1.15.0" is missing.

**Comment by BIBOLV** [comment]
@testuser7 could you please check?

**Comment by weetmuts** [comment]
Yeah, I think it was this line that got lost:
ADD https://api.github.com/repos/wmbusmeters/wmbusmeters/git/refs/heads/master version.json
it has been re-added to wmbusmeters/docker/Dockerfile

Should I build a 1.16.0 release?

**Comment by testuser7** [comment]
This join in workflow doesn't seem to work: `join('release-', github.ref_name)`

**Comment by weetmuts** [comment]
@testuser7 So it does not have anything to do with the ADD version.json line?

**Comment by weetmuts** [comment]
Oh, well, rebuilding with new tag. Perhaps it starts working again.....

**Comment by testuser7** [comment]
Fixed: https://github.com/wmbusmeters/wmbusmeters/pull/1186

**Comment by testuser7** [comment]
One more PR: https://github.com/wmbusmeters/wmbusmeters/pull/1187

**Comment by weetmuts** [comment]
Many thanks @testuser7 ! It looks like 1.16.1 was properly released on dockerhub. Right?

**Comment by testuser7** [comment]
Yes, the new tag is correct.
