### ISSUE TITLE
Please add support for this unknown mfct,media,version combination wme5.5 / qwater

### ISSUE THREAD

**Issue by bilbo-b** [wmbusmeters/wmbusmeters#1201]
auto driver detects wme5.5
but according to analysis "best" driver is qwater. Also qwater has mqtt-discovery in HA addon, wme5.5 has not.

https://wmbusmeters.org/analyze/49449344887070141a07780dff5f350082940000100007c113ffff46390000ff2c100000001d32983600000080008000800080008000800080010000000000070069012f046d3a0d0433:qwater

**Comment by learnlinuxnow** [comment]
Same here...

As it looks qheat has the same problem

**Comment by folfy** [comment]
Remark: Auto-detect should be fixed now with #1540
