### ISSUE TITLE
Please add support for this unknown mfct,media,version combination wme5.5 / qwater

### ISSUE THREAD

**Issue by bilbo-b** [wmbusmeters/wmbusmeters#1202]
auto driver does not recognise this combination
qwater seems to work correctly

https://wmbusmeters.org/analyze/49449344116853141a06780dff5f3500825a00005e0107c113ffff32230000ff2c100000001d322722000000800080010000000000000000000000000000000200dB002f046d390d0433

**Comment by learnlinuxnow** [comment]
Same here...

As it looks qheat has the same problem

**Comment by folfy** [comment]
Remark: Auto-detect should be fixed now with #1540
