### ISSUE TITLE
Simplified Arduino Libraries?

### ISSUE THREAD

**Issue by IAmOrion** [wmbusmeters/wmbusmeters#1212]
### Type of request

Question

### OS version

N/A

### wmbusmeters version

N/A

### Your message goes here

I've finally been able to get packet data / telegram from my water meter using an Arduino and a CC1101 (E07) device.
If I use wmbusmeters.org/analyze or even the wmbusmeters program in Fedora and paste the hex I receive, it gives me all the info I need - fantastic! 

Now, I really need to be able to simplify this all for my needs, I only specifically am reading Diehl Meters (868 i W R4)
and want to be able to decode the data without needing internet or a computer,  so directly using a simple MCU such as a RP2040 or an ESP32 as a standalone device.

Could anyone help or point me in the right direction to get ALL the same information that the anaylyse function offers

`
{
    "media":"water",
    "meter":"izar",
    "name":"",
    "id":"REDACTED",
    "last_month_total_m3":19.641,
    "remaining_battery_life_y":13.5,
    "total_m3":20.069,
    "transmit_period_s":8,
    "current_alarms":"no_alarm",
    "last_month_measure_date":"2024-02-29",
    "manufacture_year":"2022",
    "prefix":"REDACTED",
    "previous_alarms":"no_alarm",
    "serial_number":"REDACTED",
    "timestamp":"2024-03-14T01:44:29Z"
}
`

I found a few IZAR arduino libraries but they best they offer is ID and Meter Usage (m3) value, which is great, but I need to know the prefix and serial number also.

This one works well for example: https://github.com/maciekn/izar-wmbus-esp 
(although I did need to slightly modify it to get it working)

I tried looking for the code etc but this wmbusmeters project is obviously pretty large and I got lost in looking for what I needed

MTIA

**Comment by BIBOLV** [comment]
Hi, check [this](https://github.com/SzczepanLeon/esphome-components).
