### ISSUE TITLE
Create new driver - how update addon on it?

### ISSUE THREAD

**Issue by kzajac83** [wmbusmeters/wmbusmeters#1213]
### Type of request

Question

### HAOS version

Current

### wmbusmeters version

Current

### Your message goes here

Dear All.

Create [new driver ](https://github.com/wmbusmeters/wmbusmeters/issues/1211#issuecomment-1996187253) for my water meter, is not ideal but general working.

How update HA add-on for my new driver?

BR, Krzysiek

**Comment by BIBOLV** [comment]
Currently, proper way to get your driver in HA addon would be to create [PR](https://github.com/wmbusmeters/wmbusmeters-ha-addon/blob/main/CONTRIBUTING.md) and add it in HA addon. In future - @weetmuts is working on new driver functionality that will allow users to create and deploy new drivers for themselves more easily.

**Comment by kzajac83** [comment]
Thank you @BIBOLV but I think is too early to put in repository my driver, error codes and manufacturer specification I need decode first.

However maybe there are  workaround? I jump into HA OS, switch to 2nd console, login to root and found in docker directories wmbusmeteres file.

Unfortunately HA seems have no sshd server to copy/replace file but if I somehow replace wmbusmeteres file in docker dir then should be working?

**Comment by BIBOLV** [comment]
Any changes you make to container will be lost after restart. In this case option for you would be to fork ha-addon repo, make changes there, build your own addon and install it. Once tested you can create PR with driver.
