### ISSUE TITLE
No Telegram

### ISSUE THREAD

**Issue by Benleni17** [wmbusmeters/wmbusmeters#1226]
### Type of request

Question

### OS version

12.1

### wmbusmeters version

1.12.0

### Your message goes here

Happy Easter! I haven't received any telegrams since yesterday. The log says not found in archive. Could this be the problem of telegrams not being received? Greets Benedikt

`MQTT Discovery ...
tar: wmbusmeters-master/ha-addon/mqtt_discovery: not found in archive
 Adding meter: MainWater ...
  Add/update topic: homeassistant/sensor/wmbusmeters/76406477_external_temperature_c/config
  Add/update topic: homeassistant/sensor/wmbusmeters/76406477_flow_temperature_c/config
  Add/update topic: homeassistant/sensor/wmbusmeters/76406477_rssi_dbm/config
  Add/update topic: homeassistant/binary_sensor/wmbusmeters/76406477_status_burst/config
  Add/update topic: homeassistant/binary_sensor/wmbusmeters/76406477_status_dry/config
  Add/update topic: homeassistant/binary_sensor/wmbusmeters/76406477_status_leak/config
  Add/update topic: homeassistant/binary_sensor/wmbusmeters/76406477_status_reversed/config
  Add/update topic: homeassistant/sensor/wmbusmeters/76406477_target_m3/config
  Add/update topic: homeassistant/sensor/wmbusmeters/76406477_total_m3/config
MQTT Discovery cleanup...
[10:48:25] INFO: Running wmbusmeters ...
Started auto im871a[00103512] on /dev/ttyUSB0 listening on c1`

**Comment by pschonmann** [comment]
Hi, ive almost same problem.
Im tyring to first setup with rtl-sdr

HA
```
Core 2024.4.1
Supervisor 2024.03.1
Operating System 12.1
Frontend 20240404.1
wmbus installed as addon v 1.16.1
```

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[22:38:13] INFO: CONFIG_CONF ...
[22:38:13] INFO: {"device":"rtlwmbus:t1","donotprobe":"/dev/ttyAMA0","format":"json","logfile":"/dev/stdout","loglevel":"normal","logtelegrams":false,"shell":"/wmbusmeters/mosquitto_pub.sh \"wmbusmeters/$METER_NAME\" \"$METER_JSON\""}
[22:38:13] INFO: CONFIG_METERS ...
[22:38:13] INFO: []
[22:38:13] INFO: Syncing wmbusmeters configuration ...
[22:38:13] INFO: Registering meters ...
[22:38:13] INFO: Generating MQTT configuration ... 
[22:38:13] INFO: Broker core-mosquitto will be used.
[22:38:13] INFO: 
MQTT Discovery ...
[22:38:13] INFO: MQTT Discovery cleanup...
[22:38:14] INFO: Starting web configuration service.
[22:38:14] INFO: Running wmbusmeters ...
Started config rtlwmbus[00000001] listening on t1
No meters configured. Printing id:s of all telegrams heard!
[22:38:15] INFO: Starting Nginx...
2024/04/07 22:38:15 [notice] 84#84: using the "epoll" event method
2024/04/07 22:38:15 [notice] 84#84: nginx/1.24.0
2024/04/07 22:38:15 [notice] 84#84: OS: Linux 6.6.20-haos
2024/04/07 22:38:15 [notice] 84#84: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2024/04/07 22:38:15 [notice] 84#84: start worker processes
2024/04/07 22:38:15 [notice] 84#84: start worker process 229
```
