### ISSUE TITLE
Cannot decrypt this frame

### ISSUE THREAD

**Issue by Jerome-Rauch** [wmbusmeters/wmbusmeters#1234]
Hello,

https://wmbusmeters.org/analyze/24442d2c13336767300d8d2088422bf8222f9e6f817289da7584cfaf7f0c106c0267455633:auto:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Do you know what mean the error we have here ?

**Comment by weetmuts** [comment]
Its a compressed telegram, it needs a full length telegram first before it can understand the compressed telegram.
See if you can find a longer telegram in the logs. Try your telegram and key with that one.
