### ISSUE TITLE
Water 5.5 Qundis

### ISSUE THREAD

**Issue by cool338** [wmbusmeters/wmbusmeters#1237]
Explain the problem..... 

https://wmbusmeters.org/analyze/49449344806281141a063246780dff5f350082c20035cdB226a05d9da9de22ecef0B3ec22a8381cd96234e7ca10a56c23e189dd3de4c7B1292161162681acB9559e456f314699da396d39f29046d320B0634675d 

[12:50:51][V][rxLoop:167]: Have 86 bytes from CC1101 Rx, RSSI: -51 dBm LQI: 128
[12:50:51][D][mbus:013]: Processing C1 A frame
[12:50:51][V][mbus:017]: Frame: 49449344806281141A063246780DFF5F350082C20035CDB226A05D9DA9DE22ECEF0B3EC22A8381CD96234E7CA10A56C23E189DD3DE4C7B1292161162681ACB9559E456F314699DA396D39F29046D320B0634675D (84) [with CRC]
[12:50:51][V][mbus:095]: Validating CRC for Block1
[12:50:51][V][crc:031]:     calculated: 0x3246, read: 0x3246
[12:50:51][V][mbus:115]: Validating CRC for Block2
[12:50:51][V][crc:031]:     calculated: 0xA9DE, read: 0xA9DE
[12:50:51][V][mbus:115]: Validating CRC for Block3
[12:50:51][V][crc:031]:     calculated: 0x56C2, read: 0x56C2
[12:50:51][V][mbus:115]: Validating CRC for Block4
[12:50:51][V][crc:031]:     calculated: 0x59E4, read: 0x59E4
[12:50:51][V][mbus:115]: Validating CRC for Block5
[12:50:51][V][crc:031]:     calculated: 0x675D, read: 0x675D
[12:50:51][V][mbus:062]: Frame: 49449344806281141A06780DFF5F350082C20035CDB226A05D9D22ECEF0B3EC22A8381CD96234E7CA10A3E189DD3DE4C7B1292161162681ACB9556F314699DA396D39F29046D320B0634 (74) [without CRC]

![PXL_20240404_165711280](https://github.com/wmbusmeters/wmbusmeters/assets/122101055/478d2940-3f53-4d34-b894-ffec267da1ce)

https://wmbusmeters.org/analyze/49449344713180141A0763FB780DFF5F350082C30035AE4F225B383E1A19394980BB13B4CBE18D33E03772CD137E1AD00C95A74D9445050DD7D0F2263E25E46FF7B89F584E890CBEA985ED94046D320B0634798D

[12:50:47][V][rxLoop:167]: Have 86 bytes from CC1101 Rx, RSSI: -58 dBm LQI: 128
[12:50:47][D][mbus:013]: Processing C1 A frame
[12:50:47][V][mbus:017]: Frame: 49449344713180141A0763FB780DFF5F350082C30035AE4F225B383E1A19394980BB13B4CBE18D33E03772CD137E1AD00C95A74D9445050DD7D0F2263E25E46FF7B89F584E890CBEA985ED94046D320B0634798D (84) [with CRC]
[12:50:47][V][mbus:095]: Validating CRC for Block1
[12:50:47][V][crc:031]:     calculated: 0x63FB, read: 0x63FB
[12:50:47][V][mbus:115]: Validating CRC for Block2
[12:50:47][V][crc:031]:     calculated: 0x1A19, read: 0x1A19
[12:50:47][V][mbus:115]: Validating CRC for Block3
[12:50:47][V][crc:031]:     calculated: 0x1AD0, read: 0x1AD0
[12:50:47][V][mbus:115]: Validating CRC for Block4
[12:50:47][V][crc:031]:     calculated: 0xF7B8, read: 0xF7B8
[12:50:47][V][mbus:115]: Validating CRC for Block5
[12:50:47][V][crc:031]:     calculated: 0x798D, read: 0x798D
[12:50:47][V][mbus:062]: Frame: 49449344713180141A07780DFF5F350082C30035AE4F225B383E394980BB13B4CBE18D33E03772CD137E0C95A74D9445050DD7D0F2263E25E46F9F584E890CBEA985ED94046D320B0634 (74) [without CRC]

![PXL_20240402_090710000](https://github.com/wmbusmeters/wmbusmeters/assets/122101055/2247f699-438c-4c72-b1fe-d79d0ee628e1)

Kann mir jemand erklären was ich falsch mache?

Und ist es möglich Rauchmelder mit zu intrigieren? 

Can someone explain to me what I'm doing wrong? 

And is it possible to integrate smoke detectors?
https://wmbusmeters.org/analyze/58442515667383020C1AEFE47AA10000000BFD0F000102046D370A06710B3402FD17000082206CE828426C1033846B7B40FF2C000F11008250FD61000082506C232601018260FD6100008360FD31000000823706606C01018270FD61000082706C01013F9C

**Comment by gotsila** [comment]
Hallo,
benutze als Treiber: qwater nicht auto auch nicht den wme5.
Interessant wäre noch welchen Empfänger-Stick du benutzt. Ich benutze den iM871A-USB - Wireless M-Bus USB-adapter 868 MHz und damit habe ich in einem 3 Familienhaus einige qwater und qheat am laufen.

**Comment by cool338** [comment]
> Hallo, benutze als Treiber: qwater nicht auto auch nicht den wme5. Interessant wäre noch welchen Empfänger-Stick du benutzt. Ich benutze den iM871A-USB - Wireless M-Bus USB-adapter 868 MHz und damit habe ich in einem 3 Familienhaus einige qwater und qheat am laufen.

moin,

Also laut Wasser Uhr 2,138m³ im daten Paket steht was anderes.
{
    "media":"water",
    "meter":"qwater",
    "name":"",
    "id":"14803171",
    "due_date":"2024-12-25",
    "due_17_date":"2048-11-18",
    "due_17_date_m3":68661.528,
    "due_date_m3":66231.797,
    "total_m3":199690.017,
    "meter_datetime":"2024-04-28 08:12",
    "status":"OK",
    "timestamp":"2024-04-28T07:15:58Z"
}
49449344713180141a07780dff5f3500822400357a0862603f6835da9868Bc193c97e7f164126B1B156668aB71195B91d7120642e850e0ac4ef057fe7df0811e8f2981ad046d0c081c34


hin und wieder bekomm ich auch so welche Pakete

`[09:16:45][V][mbus:017]: Frame: 48449344713180141A0758687A250030253E2A8A3C6EE9DAF3D8715ACEDB29E343B9FC9847121AD193FA5083810D052224697CA3F001D5484E2977A4F9073923608C4D1B69CB3C326CFFFF046D10081C34F2A1 (83) [with CRC]
[09:16:45][V][mbus:095]: Validating CRC for Block1
[09:16:45][V][crc:031]:     calculated: 0x5868, read: 0x5868
[09:16:45][V][mbus:115]: Validating CRC for Block2
[09:16:45][V][crc:031]:     calculated: 0xCEDB, read: 0xCEDB
[09:16:45][V][mbus:115]: Validating CRC for Block3
[09:16:45][V][crc:031]:     calculated: 0x0522, read: 0x0522
[09:16:45][V][mbus:115]: Validating CRC for Block4
[09:16:45][V][crc:031]:     calculated: 0x608C, read: 0x608C
[09:16:45][V][mbus:115]: Validating CRC for Block5
[09:16:45][V][crc:031]:     calculated: 0xF2A1, read: 0xF2A1
[09:16:45][V][mbus:062]: Frame: 48449344713180141A077A250030253E2A8A3C6EE9DAF3D8715A29E343B9FC9847121AD193FA5083810D24697CA3F001D5484E2977A4F90739234D1B69CB3C326CFFFF046D10081C34 (73) [without CRC]`


ich nutze CC1101 Antennen und esp32. Alles in HA

TECNOIOT 2pcs CC1101 868MHz Wireless Module Long Distance Transmission with Antenna
[https://www.amazon.de/dp/B07RH67FWV?psc=1&ref=ppx_yo2ov_dt_b_product_details](url)

MfG

**Comment by gotsila** [comment]
Morgen,
fragst du nur c1 Protokoll ab? bei mir Device= /dev/ttyUSB1:im871a:c1
Weil das Datenpaket sieht grundlegend falsch aus. Due_17_date sollte letzte Tag vom letzen Monat sein.
Ansonsten würde ich empfehlen mal nen anderen Stick (idealerweise den  iM871A-USB) probieren, evtl. bei nem Kollegen leihen. ich setzte das auch alles unter HA ein.
Andere Frage hast du noch mehr Zähler oder ist das der einzige.

Bei mir sieht das so aus. :
`(shell) env "METER_JSON={"media":"warm water","meter":"qwater","name":"51946926_qwater_warm_dg","id":"51946926","due_date":"2023-12-31","due_17_date":"2024-03-31","due_17_date_m3":6.856,"due_date_m3":0.034,"error_date":"2128-03-31","total_m3":9.757,"volume_flow_m3h":0,"meter_datetime":"2024-04-28 08:39","status":"OK","timestamp":"2024-04-28T07:39:33Z","device":"im871a[00103921]","rssi_dbm":-74}"`

in HA:
![image](https://github.com/wmbusmeters/wmbusmeters/assets/44124658/f606d9e0-4e3e-46cd-8a09-6095ad65f8b1)

**Comment by cool338** [comment]
Moin,
Also ich nutze den code hier der ist von https://github.com/zibous/ha-watermeter
womöglich da drin der fehler?
Es läuft alles über esphome



`
## ------------------------------------------------------------------
##           WMBUS CC1101 --> ESP32 az-delivery-devkit-v4
## ------------------------------------------------------------------
##
##
##                                                               o 1 (3.3V)
##                                                               |
##   ╭――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――o―╮
##   |                                                             |
##   |                          EP32                               |
## - | 5v               az-delivery-devkit-v4                      | -- ANT
##   |                                                             |
##   |                          16 17 5  18 19               23    |
##   ╰――x――x――x――x――x――x――x――x――o――x――o――o――o――o――o――o――o――o――o――o―╯
##                              |  |  |  |  |                 |   |
##                              o  |  |  o  |                 |   ╰-o - 2 (GND)
##                              7  o  |  4  o                 o
##                            GDO0 6  | CLK 5                 3
##                               GD02 o    MISO              M0SI
##                                    8
##                                   CSN
##
## ------------------------------------------------------------------
wmbus:
  mosi_pin: GPIO23  ## SI:   braun   3: MOSI Attached to Hardware SPI controller MOSI SPI Interface
  miso_pin: GPIO19  ## SO:   grün    5: MISO Attached to Hardware SPI controller MISO SPI Interface
  clk_pin: GPIO18   ## SCLK: violett 4: SCK  Attached to Hardware SPI controller CLK
  cs_pin: GPIO05    ## CSN:  orange  8: CSN  Attached to Hardware SPI controller
  gdo0_pin: GPIO16  ## GD00: gelb    7: RX Clock output. High Impedance !
  gdo2_pin: GPIO17  ## GD02: weiss   6: TX FIFO status signals. High Impedance !

  # log_unknown (Optional): Show telegrams from not configured meters in log. Defaults to False
  log_unknown: False

  ## -------------------------------------------------
  ## Using wmbusmeters i a pipe (optional)
  ## uncomment for using
  ## -------------------------------------------------
  # clients:
  #  - name: "wmbusmeters"
  #    ip_address: !secret wmbusmeter_host
  #    port: 7227
  #    format: rtlwMBus
  #    transport: UDP

  ## -------------------------------------------------
  ## setting: wmbusmeters.conf on wbusmeters server
  ## -------------------------------------------------
  ## loglevel: normal
  ## device: rtlwmbus:CMD(nc -lku 7227)
  ## donotprobe: /dev/ttyAMA0
  ## logtelegrams: false
  ## format: json
  ## logfile: /dev/stdout
  ## shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"

  ## -------------------------------------------------
  ## led blink mode (optional) xx = PIN
  ## -------------------------------------------------
  # led_pin: GPIOxx
  # led_blink_time: "100ms"

## ---------------------------------------------------
## BINARY SENSOR
## ---------------------------------------------------
binary_sensor:

  # simulate led state (updated by id: "waterdisplay")
  - platform: template
    name: "Wasseruhr Status Led"
    id: statusled
    icon: mdi:led-outline
    entity_category: "diagnostic"
    lambda: "return id(current_value) > 0;"

## ---------------------------------------------------
## SENSORS
## ---------------------------------------------------
sensor:

  - platform: wmbus

    # Meter ID (usually from sticker). Can be specified as decimal or hex.
    # only HEX is working for my watermeter !
    # see: https://github.com/SzczepanLeon/esphome-components/issues/6
    # edit watermeterid in the secrets file
    # add_prefix: enable/disable add watermeterid to lqi, rssi, total_water_m3
    meter_id: 0
    type: qwater
    add_prefix: false

    # The LQI value reported by the CC1101 is a 7 bit unsigned number with a range from 0 to 127.
    # Note that a lower value indicates a better link.
    # The LQI of a received packet will be bad (higher number) when there is lot of interference.
    lqi:
      id: wmbus_cc1101_lqi
      name: "${friendly_name} CC1101 LQI"
      entity_category: "diagnostic"
      unit_of_measurement: "lqi"
      state_class: "measurement"

    # The RSSI value reported by the CC1101 is a 8 bit signed number with an effective
    # range from -138 dBm to -10.5 dBm when the CC1101 is operating around 868 MHz.
    # RSSI stands for received signal strength (power) indication (in dBm).
    # A higher value indicates higher power. (internal only) see id: cc1101_rssi
    rssi:
      id: wmbus_cc1101_rssi
      name: "${friendly_name} CC1101 RSSI"
      filters:
        - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
      unit_of_measurement: "%"
      entity_category: "diagnostic"
      state_class: "measurement"
      icon: mdi:rss

    # get the total watermter m3 from the wmbus telegram, log the timestamp
    # for the last reading  and calculates the statitics value
    # and update all sensors: last_value, watercurrent, hour_value, daily_value
    # week_value, month_value, year_value and watermeter_lastupdate
    total_water_m3:
      id: "waterdisplay"
      name: "Wasseruhr Anzeige"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: "water"
      accuracy_decimals: 3
      icon: mdi:counter

      # Send the value periodically with the specified time interval.
      # If the sensor value changes during the interval the interval will not reset.
      # The last value of the sensor will be sent. 60s means, that every minute the
      # last state will be published.
      # The IZAR Watermeter will publish data all 8s (see transmit_period_s),
      # but we need this only evers minute.
      # filters:
      #   - heartbeat: 60s

      # update and calulatet all watermeter sensor data values
      on_value:
        then:
          - lambda: |-
              if ((id(last_value) > 0.00) and (id(waterdisplay).state)>(id(last_value)) ) {
                id(cc1101_state) = 2;
                ESP_LOGI("wmbus", "Water Display value: %.3f, last value: %.3f", id(waterdisplay).state, id(last_value));
                id(current_value) = float(id(waterdisplay).state-id(last_value)) * 1000.00;
                id(watercurrent).publish_state(id(current_value));
                id(hour_value)+=id(current_value);
                id(waterhour).publish_state(id(hour_value));
                id(daily_value)+=id(current_value);
                id(waterday).publish_state(id(daily_value));
                id(week_value)+=id(current_value);
                id(waterweek).publish_state(id(week_value));
                id(year_value)+=id(current_value);
                id(wateryear).publish_state(id(year_value));
                ESP_LOGD("wmbus", "Set current value to %.3f litre and publish the data", id(current_value));
                if ( ${service_enabled} == true){
                  id(post_device_state).execute();
                }else{
                  ESP_LOGD("wmbus", "Data Service to host disabled");
                }
              }else{
                id(current_value) = 0.00;
                id(cc1101_state) = 1;
                id(watercurrent).publish_state(id(current_value));
                ESP_LOGI("wmbus", "Reset current value to: %.3f, Waterdisplay value: %.3f, last value: %.3f", id(current_value), id(waterdisplay).state, id(last_value));
              }
              id(last_value)=id(waterdisplay).state;

          # update the watermeter_lastupdate timestamp for the last waterdisplay state
          - text_sensor.template.publish:
              id: watermeter_lastupdate
              state: !lambda return id(time_sntp).now().strftime("%Y-%m-%dT%H:%M:%S %Z");

          # update watermeter_read_timeout the reading timeout for the watermeter display
          - sensor.template.publish:
              id: watermeter_read_timeout
              state: !lambda |-
                int time_used = ( millis() - id(send_millisecond) );
                ESP_LOGD("wmbus", "Diff millisecond is: %d", time_used);
                id(send_millisecond) = millis();
                return float(time_used)/1000;

          # update the watermeter status
          - script.execute: set_status_message

          # update the status led (statusled)
          - binary_sensor.template.publish:
              id: statusled
              state: !lambda "return id(current_value) > 0;"

    # water current month (wM-Bus v2.1.4)
    current_month_total_water_l:
      name: Wasser Monat
      id: "watermonth"
      accuracy_decimals: 2
      unit_of_measurement: "L"
      icon: mdi:water-outline
      state_class: total_increasing
      device_class: "water"

    # get the last month total watermter m3 from the wmbus telegram  (wM-Bus 2.1.10)
    last_month_total_water_m3:
      name: "Wasseruhr Anzeige letzter Monat"
      id: "waterdisplay_lastmonth"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: "water"
      accuracy_decimals: 3
      icon: mdi:counter

    # get the battery life time (wM-Bus v2.1.4)
    remaining_battery_life_y:
      name: "Wasseruhr Batterielebensdauer"
      id: "watermeter_batterie"
      accuracy_decimals: 2
      unit_of_measurement: "Jahre"
      state_class: "measurement"
      entity_category: "diagnostic"
      icon: mdi:battery

    # get the last transmit periode (wM-Bus v2.1.4)
    transmit_period_s:
      name: "Wasseruhr Update Intervall"
      id: "watermeter_transmit_periode"
      unit_of_measurement: "sec"
      state_class: "measurement"
      accuracy_decimals: 2
      entity_category: "diagnostic"
      icon: mdi:timelapse

    ## get the current watermeter alarms and publish the text message (wM-Bus 2.1.10)
    ## see: id: watermeter_alarm_message
    current_alarms:
      id: "watermeter_current_alarms"
      name: "Wasseruhr Alarm Code"
      entity_category: "diagnostic"
      icon: mdi:message-alert-outline
      on_value:
        then:
          - lambda: |-
              int error_code = int(x);
              std::string message = "";
              if(error_code==0){
                  message = id(alarm_error_text)[error_code];
                  id(watermeter_alarm_message).publish_state(message);
                  ESP_LOGD("wmbus", "Alarm message: %s, error code: %d", message, error_code);
              }else{
                for (int i = 1; i < 10; ++i) {
                  if (error_code & (1 << i)) {
                    if (!message.empty()) {
                      message += ", ";
                    }
                    message += id(alarm_error_text)[i];
                  }
                }
                id(watermeter_alarm_message).publish_state(message);
                ESP_LOGW("wmbus", "WARNING Alarm message: %s, error code: %d", message.c_str(), error_code);
                id(watermeter_alarm_timestamp).publish_state(id(time_sntp).now().strftime("%Y-%m-%dT%H:%M:%S %Z").c_str());
              }

    ## get the prevois watermeter alarms and publish the text message (wM-Bus 2.1.10)
    ## see: id: watermeter_alarm_perv_message
    previous_alarms:
      id: "watermeter_previous_alarms"
      name: "Wasseruhr Alarm Code voriger"
      icon: mdi:message-alert
      entity_category: "diagnostic"
      on_value:
        then:
          - lambda: |-
              int error_code = int(x);
              std::string message = "";
              if(error_code==0){
                  message = id(alarm_error_text)[error_code];
                  id(watermeter_alarm_message).publish_state(message);
                  ESP_LOGD("wmbus", "Alarm message: %s, error code: %d", message, error_code);
              }else{
                for (int i = 1; i < 10; ++i) {
                  if (error_code & (1 << i)) {
                    if (!message.empty()) {
                      message += ", ";
                    }
                    message += id(alarm_error_text)[i];
                  }
                }
                ESP_LOGW("wmbus", "WARNING Alarm message: %s, error code: %d", message.c_str(), error_code);
                id(watermeter_alarm_timestamp).publish_state(id(time_sntp).now().strftime("%Y-%m-%dT%H:%M:%S %Z").c_str());
              }
              id(watermeter_alarm_perv_message).publish_state(message);
              if(id(watermeter_alarm_timestamp).has_state() == false) {
                id(watermeter_alarm_timestamp).publish_state("--");
              }
`

**Comment by cool338** [comment]
Moin,
Also ich nutze den code hier der ist von https://github.com/zibous/ha-watermeter
womöglich da drin der fehler?
Es läuft alles über esphome



`
## ------------------------------------------------------------------
##           WMBUS CC1101 --> ESP32 az-delivery-devkit-v4
## ------------------------------------------------------------------
##
##
##                                                               o 1 (3.3V)
##                                                               |
##   ╭――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――x――o―╮
##   |                                                             |
##   |                          EP32                               |
## - | 5v               az-delivery-devkit-v4                      | -- ANT
##   |                                                             |
##   |                          16 17 5  18 19               23    |
##   ╰――x――x――x――x――x――x――x――x――o――x――o――o――o――o――o――o――o――o――o――o―╯
##                              |  |  |  |  |                 |   |
##                              o  |  |  o  |                 |   ╰-o - 2 (GND)
##                              7  o  |  4  o                 o
##                            GDO0 6  | CLK 5                 3
##                               GD02 o    MISO              M0SI
##                                    8
##                                   CSN
##
## ------------------------------------------------------------------
wmbus:
  mosi_pin: GPIO23  ## SI:   braun   3: MOSI Attached to Hardware SPI controller MOSI SPI Interface
  miso_pin: GPIO19  ## SO:   grün    5: MISO Attached to Hardware SPI controller MISO SPI Interface
  clk_pin: GPIO18   ## SCLK: violett 4: SCK  Attached to Hardware SPI controller CLK
  cs_pin: GPIO05    ## CSN:  orange  8: CSN  Attached to Hardware SPI controller
  gdo0_pin: GPIO16  ## GD00: gelb    7: RX Clock output. High Impedance !
  gdo2_pin: GPIO17  ## GD02: weiss   6: TX FIFO status signals. High Impedance !

  # log_unknown (Optional): Show telegrams from not configured meters in log. Defaults to False
  log_unknown: False

  ## -------------------------------------------------
  ## Using wmbusmeters i a pipe (optional)
  ## uncomment for using
  ## -------------------------------------------------
  # clients:
  #  - name: "wmbusmeters"
  #    ip_address: !secret wmbusmeter_host
  #    port: 7227
  #    format: rtlwMBus
  #    transport: UDP

  ## -------------------------------------------------
  ## setting: wmbusmeters.conf on wbusmeters server
  ## -------------------------------------------------
  ## loglevel: normal
  ## device: rtlwmbus:CMD(nc -lku 7227)
  ## donotprobe: /dev/ttyAMA0
  ## logtelegrams: false
  ## format: json
  ## logfile: /dev/stdout
  ## shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"

  ## -------------------------------------------------
  ## led blink mode (optional) xx = PIN
  ## -------------------------------------------------
  # led_pin: GPIOxx
  # led_blink_time: "100ms"

## ---------------------------------------------------
## BINARY SENSOR
## ---------------------------------------------------
binary_sensor:

  # simulate led state (updated by id: "waterdisplay")
  - platform: template
    name: "Wasseruhr Status Led"
    id: statusled
    icon: mdi:led-outline
    entity_category: "diagnostic"
    lambda: "return id(current_value) > 0;"

## ---------------------------------------------------
## SENSORS
## ---------------------------------------------------
sensor:

  - platform: wmbus

    # Meter ID (usually from sticker). Can be specified as decimal or hex.
    # only HEX is working for my watermeter !
    # see: https://github.com/SzczepanLeon/esphome-components/issues/6
    # edit watermeterid in the secrets file
    # add_prefix: enable/disable add watermeterid to lqi, rssi, total_water_m3
    meter_id: 0
    type: qwater
    add_prefix: false

    # The LQI value reported by the CC1101 is a 7 bit unsigned number with a range from 0 to 127.
    # Note that a lower value indicates a better link.
    # The LQI of a received packet will be bad (higher number) when there is lot of interference.
    lqi:
      id: wmbus_cc1101_lqi
      name: "${friendly_name} CC1101 LQI"
      entity_category: "diagnostic"
      unit_of_measurement: "lqi"
      state_class: "measurement"

    # The RSSI value reported by the CC1101 is a 8 bit signed number with an effective
    # range from -138 dBm to -10.5 dBm when the CC1101 is operating around 868 MHz.
    # RSSI stands for received signal strength (power) indication (in dBm).
    # A higher value indicates higher power. (internal only) see id: cc1101_rssi
    rssi:
      id: wmbus_cc1101_rssi
      name: "${friendly_name} CC1101 RSSI"
      filters:
        - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
      unit_of_measurement: "%"
      entity_category: "diagnostic"
      state_class: "measurement"
      icon: mdi:rss

    # get the total watermter m3 from the wmbus telegram, log the timestamp
    # for the last reading  and calculates the statitics value
    # and update all sensors: last_value, watercurrent, hour_value, daily_value
    # week_value, month_value, year_value and watermeter_lastupdate
    total_water_m3:
      id: "waterdisplay"
      name: "Wasseruhr Anzeige"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: "water"
      accuracy_decimals: 3
      icon: mdi:counter

      # Send the value periodically with the specified time interval.
      # If the sensor value changes during the interval the interval will not reset.
      # The last value of the sensor will be sent. 60s means, that every minute the
      # last state will be published.
      # The IZAR Watermeter will publish data all 8s (see transmit_period_s),
      # but we need this only evers minute.
      # filters:
      #   - heartbeat: 60s

      # update and calulatet all watermeter sensor data values
      on_value:
        then:
          - lambda: |-
              if ((id(last_value) > 0.00) and (id(waterdisplay).state)>(id(last_value)) ) {
                id(cc1101_state) = 2;
                ESP_LOGI("wmbus", "Water Display value: %.3f, last value: %.3f", id(waterdisplay).state, id(last_value));
                id(current_value) = float(id(waterdisplay).state-id(last_value)) * 1000.00;
                id(watercurrent).publish_state(id(current_value));
                id(hour_value)+=id(current_value);
                id(waterhour).publish_state(id(hour_value));
                id(daily_value)+=id(current_value);
                id(waterday).publish_state(id(daily_value));
                id(week_value)+=id(current_value);
                id(waterweek).publish_state(id(week_value));
                id(year_value)+=id(current_value);
                id(wateryear).publish_state(id(year_value));
                ESP_LOGD("wmbus", "Set current value to %.3f litre and publish the data", id(current_value));
                if ( ${service_enabled} == true){
                  id(post_device_state).execute();
                }else{
                  ESP_LOGD("wmbus", "Data Service to host disabled");
                }
              }else{
                id(current_value) = 0.00;
                id(cc1101_state) = 1;
                id(watercurrent).publish_state(id(current_value));
                ESP_LOGI("wmbus", "Reset current value to: %.3f, Waterdisplay value: %.3f, last value: %.3f", id(current_value), id(waterdisplay).state, id(last_value));
              }
              id(last_value)=id(waterdisplay).state;

          # update the watermeter_lastupdate timestamp for the last waterdisplay state
          - text_sensor.template.publish:
              id: watermeter_lastupdate
              state: !lambda return id(time_sntp).now().strftime("%Y-%m-%dT%H:%M:%S %Z");

          # update watermeter_read_timeout the reading timeout for the watermeter display
          - sensor.template.publish:
              id: watermeter_read_timeout
              state: !lambda |-
                int time_used = ( millis() - id(send_millisecond) );
                ESP_LOGD("wmbus", "Diff millisecond is: %d", time_used);
                id(send_millisecond) = millis();
                return float(time_used)/1000;

          # update the watermeter status
          - script.execute: set_status_message

          # update the status led (statusled)
          - binary_sensor.template.publish:
              id: statusled
              state: !lambda "return id(current_value) > 0;"

    # water current month (wM-Bus v2.1.4)
    current_month_total_water_l:
      name: Wasser Monat
      id: "watermonth"
      accuracy_decimals: 2
      unit_of_measurement: "L"
      icon: mdi:water-outline
      state_class: total_increasing
      device_class: "water"

    # get the last month total watermter m3 from the wmbus telegram  (wM-Bus 2.1.10)
    last_month_total_water_m3:
      name: "Wasseruhr Anzeige letzter Monat"
      id: "waterdisplay_lastmonth"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: "water"
      accuracy_decimals: 3
      icon: mdi:counter

    # get the battery life time (wM-Bus v2.1.4)
    remaining_battery_life_y:
      name: "Wasseruhr Batterielebensdauer"
      id: "watermeter_batterie"
      accuracy_decimals: 2
      unit_of_measurement: "Jahre"
      state_class: "measurement"
      entity_category: "diagnostic"
      icon: mdi:battery

    # get the last transmit periode (wM-Bus v2.1.4)
    transmit_period_s:
      name: "Wasseruhr Update Intervall"
      id: "watermeter_transmit_periode"
      unit_of_measurement: "sec"
      state_class: "measurement"
      accuracy_decimals: 2
      entity_category: "diagnostic"
      icon: mdi:timelapse

    ## get the current watermeter alarms and publish the text message (wM-Bus 2.1.10)
    ## see: id: watermeter_alarm_message
    current_alarms:
      id: "watermeter_current_alarms"
      name: "Wasseruhr Alarm Code"
      entity_category: "diagnostic"
      icon: mdi:message-alert-outline
      on_value:
        then:
          - lambda: |-
              int error_code = int(x);
              std::string message = "";
              if(error_code==0){
                  message = id(alarm_error_text)[error_code];
                  id(watermeter_alarm_message).publish_state(message);
                  ESP_LOGD("wmbus", "Alarm message: %s, error code: %d", message, error_code);
              }else{
                for (int i = 1; i < 10; ++i) {
                  if (error_code & (1 << i)) {
                    if (!message.empty()) {
                      message += ", ";
                    }
                    message += id(alarm_error_text)[i];
                  }
                }
                id(watermeter_alarm_message).publish_state(message);
                ESP_LOGW("wmbus", "WARNING Alarm message: %s, error code: %d", message.c_str(), error_code);
                id(watermeter_alarm_timestamp).publish_state(id(time_sntp).now().strftime("%Y-%m-%dT%H:%M:%S %Z").c_str());
              }

    ## get the prevois watermeter alarms and publish the text message (wM-Bus 2.1.10)
    ## see: id: watermeter_alarm_perv_message
    previous_alarms:
      id: "watermeter_previous_alarms"
      name: "Wasseruhr Alarm Code voriger"
      icon: mdi:message-alert
      entity_category: "diagnostic"
      on_value:
        then:
          - lambda: |-
              int error_code = int(x);
              std::string message = "";
              if(error_code==0){
                  message = id(alarm_error_text)[error_code];
                  id(watermeter_alarm_message).publish_state(message);
                  ESP_LOGD("wmbus", "Alarm message: %s, error code: %d", message, error_code);
              }else{
                for (int i = 1; i < 10; ++i) {
                  if (error_code & (1 << i)) {
                    if (!message.empty()) {
                      message += ", ";
                    }
                    message += id(alarm_error_text)[i];
                  }
                }
                ESP_LOGW("wmbus", "WARNING Alarm message: %s, error code: %d", message.c_str(), error_code);
                id(watermeter_alarm_timestamp).publish_state(id(time_sntp).now().strftime("%Y-%m-%dT%H:%M:%S %Z").c_str());
              }
              id(watermeter_alarm_perv_message).publish_state(message);
              if(id(watermeter_alarm_timestamp).has_state() == false) {
                id(watermeter_alarm_timestamp).publish_state("--");
              }
`

**Comment by gotsila** [comment]
Uff, also dazu kann ich nix sagen. Aber hier sind wir ja bei wmbusmeters und ich nutze das HA-AddOn,  
https://github.com/wmbusmeters/wmbusmeters-ha-addon

Denke die Frage wäre in dem anderen Fork besser aufgehoben, deshalb gibts hier vermutlich keine Hilfe.

**Comment by cool338** [comment]
> Uff, also dazu kann ich nix sagen. Aber hier sind wir ja bei wmbusmeters und ich nutze das HA-AddOn, https://github.com/wmbusmeters/wmbusmeters-ha-addon
> 
> Denke die Frage wäre in dem anderen Fork besser aufgehoben, deshalb gibts hier vermutlich keine Hilfe.

Ja das ist auch das Problem wohl. 

Das addon kann nicht auf den esp32 zugreifen und deswegen klappt es wohl net so ganz. 

Dennoch danke sehr für die Hilfe :)

MfG

**Comment by sippeeey** [comment]
@cool338 ich habe genau das gleiche Problem, dass die Werte, die ausgelesen werden, nicht der Realität entsprechen.

Beispiel: https://wmbusmeters.org/analyze/49449344708828521a072198780dff5f350082a70035865B2883cf79596625201701faccdcedd4506930ee48B78676cf439BeB7e6054de780a19938a15235695B5c3e7af7140e85Bfaefe1dd046d011307365690

Tatsächlicher Verbrauch: 1885m³

Ich setze ebenfalls das ESP32 Projekt und habe diese Antenne: https://www.amazon.de/dp/B075PFQ57G?psc=1&ref=ppx_yo2ov_dt_b_product_details (Laqiya CC1101 868MHZ Funkübertragung Antenne Transceiver Modul)

Hast du es bereits lösen können?
