### ISSUE TITLE
Add support for mfct: (GWF) Gas u Wassermesserfabrik, Switzerland

### ISSUE THREAD

**Issue by polyminthe** [wmbusmeters/wmbusmeters#1240]
### Type of request

Enhancement

### OS version

Docker - Windows

### wmbusmeters version

1.16.1 

### Your message goes here

Hi , i tried your nice addon wmbusmeters for home assistant. 
I can found with succes my water meter, but unfortunatly the driver does not exists for it.
It is write on the logs, that i should post a request here to add the support for my GWF water meter.
Do you can please add it ?

Here is the logs of my telegrams.
Many thanks in advance

(telegram) DLL L=36 C=44 (from meter SND_NR) M=1ee6 (GWF) A=01049277 VER=02 TYPE=0e (Bus/System component) (driver unknown!) DEV=rtlwmbus[00000001] RSSI=101
(wmbus) parseELL @10 45
(wmbus) parseNWL @10 45
(wmbus) parseAFL @10 45
(wmbus) parseTPL @10 45
(TPL) num encrypted blocks 2 (32 bytes and remaining unencrypted 0 bytes)
(TPL) AES CBC IV decrypting "B2646936B98782D6FC66374C0BFB31E4709E5B374DCF87D6937B091A2D06C315"
(TPL) IV E61E102963183C070606060606060606
(TPL) decrypted  "2F2F03740BA6000413932E10004413AC041000426C1F3302FD74410F0F0100A8"
(telegram) TPL CI=72 ACC=06 STS=00 CFG=6520 (accessibility synchronous AES_CBC_IV nb=2 cntn=0 ra=0 hc=0) ID=10296318 MFT=e61e VER=3c TYPE=07 (Water meter)
**telegram=|3644E61E77920401020E7210296318E61E3C07060020652F2F_03740BA6000413932E10004413AC041000426C1F3302FD74410F0F0100A8|+18**
(auto) 000   : 36 length (54 bytes)
(auto) 001   : 44 dll-c (from meter SND_NR)
(auto) 002   : e61e dll-mfct (GWF)
(auto) 004   : 77920401 dll-id (01049277)
(auto) 008   : 02 dll-version
(auto) 009   : 0e dll-type (Bus/System component)
(auto) 010   : 72 tpl-ci-field (EN 13757-3 Application Layer (long tplh))
(auto) 011   : 10296318 tpl-id (18632910)
(auto) 015   : e61e tpl-mfct (GWF)
(auto) 017   : 3c tpl-version
(auto) 018   : 07 tpl-type (Water meter)
(auto) 019   : 06 tpl-acc-field
(auto) 020   : 00 tpl-sts-field (OK)
(auto) 021   : 2065 tpl-cfg 6520 (accessibility synchronous AES_CBC_IV nb=2 cntn=0 ra=0 hc=0 )
(auto) 023   : 2f2f decrypt check bytes (OK)
(auto) 025   : 03 dif (24 Bit Integer/Binary Instantaneous value)
(auto) 026   : 74 vif (Actuality duration seconds)
(auto) 027 C?: 0BA600
(auto) 030   : 04 dif (32 Bit Integer/Binary Instantaneous value)
(auto) 031   : 13 vif (Volume l)
(auto) 032 C?: 932E1000
(auto) 036   : 44 dif (32 Bit Integer/Binary Instantaneous value storagenr=1)
(auto) 037   : 13 vif (Volume l)
(auto) 038 C?: AC041000
(auto) 042   : 42 dif (16 Bit Integer/Binary Instantaneous value storagenr=1)
(auto) 043   : 6C vif (Date type G)
(auto) 044 C?: 1F33
(auto) 046   : 02 dif (16 Bit Integer/Binary Instantaneous value)
(auto) 047   : FD vif (Second extension FD of VIF-codes)
(auto) 048   : 74 vife (Reserved)
(auto) 049 C?: 410F
(auto) 051 C?: 0F manufacturer specific data 0100A8
(shell) exec "/bin/sh"
(shell) arg "-c"
(shell) arg "/wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON""
(shell) env "METER_ID=18632910"
(shell) env "METER_NAME=GwfWaterMeter"
(shell) env "METER_TYPE=auto"
(shell) env "METER_JSON={"media":"water","meter":"auto","name":"GwfWaterMeter","id":"18632910","timestamp":"2024-04-11T11:01:15Z","device":"rtlwmbus[00000001]","rssi_dbm":101}"
(shell) env "METER_MEDIA=water"
(shell) env "METER_TIMESTAMP=2024-04-11T11:01:15Z"
(shell) env "METER_TIMESTAMP_UTC=2024-04-11T11:01:15Z"
(shell) env "METER_TIMESTAMP_UT=1712833275"
(shell) env "METER_TIMESTAMP_LT=2024-04-11 13:01:15"
(shell) env "METER_DEVICE=rtlwmbus[00000001]"
(shell) env "METER_RSSI_DBM=101"
(shell) waiting for child 274 to complete.
(shell) /bin/sh: return code 0

**Comment by regular555** [comment]
I ran into the same issue.  
Adding the line in the driver_gwfwater.cc file worked for me:

di.addDetection(MANUFACTURER_GWF, 0x07,  0x3c);

after that, I did the following:
cd wmbusmeters
./configure
make
sudo make install
