### ISSUE TITLE
Can the meter readings be used for the official utility bill?

### ISSUE THREAD

**Issue by fazer1** [wmbusmeters/wmbusmeters#1255]
### Type of request

Question

### OS version

Raspyberry Pi OS Bullseye

### wmbusmeters version

Not used yet

### Your message goes here

As the title suggests, I would like to know whether the meter readings can be used for the utility bill? As a landlord, you are obliged to provide evidence and explanations. Can the read-out telegrams be used as evidence or can they be manipulated, for example, or can meter values be challenged?

**Comment by zejn** [comment]
Hi, fazer1.

I think your question exceeds the scope of this open source project.

The software provides a technical way to read out many utility meters, but you should contact your local legal expert which can advise you under what circumstances telegram readouts would be admissible as "evidence".

As stated in LICENSE file, the software is provided "as is".
