### ISSUE TITLE
Missing File pollucomf.json

### ISSUE THREAD

**Issue by Barry-Ricoh** [wmbusmeters/wmbusmeters#1256]
### Type of request

Question

### HAOS version

2024.04

### wmbusmeters version

current

### Your message goes here

As told in the documentation Pollucom f Heatmeter is supportet. Im using that driver, and all is working well, i can See all data at the MQTT Server.
But i am not able to get an entities in HA because there is no pollucomf.json file under the MQTT section.
Also this is statet in the log. Missing pollucomf.json
Where can i find it?

**Comment by zejn** [comment]
@Barry-Ricoh 

You can add a manually added MQTT entity in HA, see the [HA documentation here](https://www.home-assistant.io/integrations/sensor.mqtt/).
