### ISSUE TITLE
Double CUL-868-433 USB stick not recognized

### ISSUE THREAD

**Issue by sectune** [wmbusmeters/wmbusmeters#1260]
### Type of request

New device support

### Meter description

Hello,
I am very sorry for the beginner question but I could not get any information from the wiki on this device and I also tried reading the open/closed issues with no avail.
I have bought the following device:
https://smart-home-komponente.de/en/products/doppel-cul-868-433-usb-stick-fur-fhem-1x-868mhz-1x-433mhz
and trying to run it with both 868 as well as the second cul with 433 in the wmbusmeters add-on in Home Assistant.
In the terminal I see that the device is recognised:
```
lrwxrwxrwx    1 root     root            13 Apr 25 00:28 usb-STM32_MapleCUL_3a5d9184-if00 -> ../../ttyACM1
lrwxrwxrwx    1 root     root            13 Apr 25 00:28 usb-STM32_MapleCUL_3a5d9184-if02 -> ../../ttyACM2
lrwxrwxrwx    1 root     root            13 Apr 25 00:28 usb-STM32_MapleCUL_3a5d9184-if04 -> ../../ttyACM3
```
However, I do get the following output when trying to run with `device=auto:t1` (nothing changed, reset config multiple times) :
```
No wmbus device detected, waiting for a device to be plugged in.
No meters configured. Printing id:s of all telegrams heard!
```

Can you maybe be so kind and give me a hint on how to proceed and what I am doing wrong? I am very grateful for any advice!

### Logged telegrams from meter in decrypted format

```shell
no telegrams logged
```

**Comment by sectune** [comment]
Still kindly looking for support

**Comment by weetmuts** [comment]
You have to do:`wmbusmeters --debug auto:t1`
and post the log here.
