### ISSUE TITLE
Apator AT-WMBUS-08-2

### ISSUE THREAD

**Issue by rambobinator** [wmbusmeters/wmbusmeters#1273]
Hi,

Thanks for the tool, i'v been using it since a while and tried to migrate to the ha addon but It doesn't seem to support driver overriding which is what i was doing until now with apator08 driver:
https://wmbusmeters.org/analyze/1c441486069c14000f0fa042f214000040030000000005ff0472Bf1400:apator08

Should i duplicate apator08 driver to apator082 or just adding detections to the current working driver ?
I would personaly prefer the first solution which allows us to add testcase, but let me know.

--
Roman

**Comment by weetmuts** [comment]
Thanks! Yes, I merged your new driver with the existing driver. So there is only a single apator08 driver that handles both.
