### ISSUE TITLE
fatal error: libxml/tree.h

### ISSUE THREAD

**Issue by Marcus54542** [wmbusmeters/wmbusmeters#1275]
### Type of request

Question

### OS version

NAME="Raspbian GNU/Linux" VERSION="11 (bullseye)"

### wmbusmeters version

the last

### Your message goes here

Hello 
I install the program on a raspberry pi 2
After loading the git

git clone [http:///github.com/weetmuts/wmbusmeters.git](http://github.com/weetmuts/wmbusmeters.git)

I run the command:
./configure; make; sudo make install

I have this error at the time of building

Building _
g++ -I/usr/include/libxml2 -Os -g -DFUZZING=false -fPIC -std=c++11 -Wall -Werror=format-security -Wno-unused-function -Ibuild src/xmq.c -c -E > build/xmq.o.src
src/xmq.c:900:9: **fatal error: libxml/tree.h**: No such file or directory
  900 | #include<libxml/tree.h>
      |         ^~~~~~~~~~~~~~~
compilation terminated.

I'm new to Linux, how can I solve this problem?
Thank you

**Comment by MichaelGrafnetter** [comment]
Hello @Marcus54542 , I had the same issue on Ubuntu and running `sudo apt install libxml2-dev`, which also upgraded the `libxml2` package helped.

**Comment by Marcus54542** [comment]
Hello @MichaelGrafnetter 
It went very badly!
I think the system is broken.
I'm going to reinstall a new version of Linux, you advise me which version to use [wmbusmeters ](https://github.com/wmbusmeters/wmbusmeters)on a raspberry pi 2.
Thank you

`
marc@compteur:~ $ sudo apt install libxml2-dev
Reading package lists... Error!
E: Unable to parse package file /var/lib/apt/lists/raspbian.raspberrypi.org_rasp                                                                                                                                                            bian_dists_bullseye_main_binary-armhf_Packages (1)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted
marc@compteur:~ $ ^C
marc@compteur:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Fetched 13.2 MB in 9s (1,454 kB/s)
Reading package lists... Done
marc@compteur:~ $ sudo apt install libxml2-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  libfuse2
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  icu-devtools libicu-dev
Suggested packages:
  icu-doc
The following NEW packages will be installed:
  icu-devtools libicu-dev libxml2-dev
0 upgraded, 3 newly installed, 0 to remove and 36 not upgraded.
Need to get 10.0 MB of archives.
After this operation, 45.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrors.ircam.fr/pub/raspbian/raspbian bullseye/main armhf icu-devtools armhf 67.1-7 [172 kB]
Get:2 http://mirrors.ircam.fr/pub/raspbian/raspbian bullseye/main armhf libicu-dev armhf 67.1-7 [9,228 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libxml2-dev armhf 2.9.10+dfsg-6.7+deb11u                                                                                                                                 4 [646 kB]
Fetched 10.0 MB in 3s (3,084 kB/s)
Can't locate Getopt/Long.pm in @INC (you may need to install the Getopt::Long module) (@INC contains: /etc/perl /usr/local/lib/arm                                                                                                          -linux-gnueabihf/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/arm-linux-gnueabihf/perl5/5.32 /usr/share/perl5 /usr/lib/arm-li                                                                                                          nux-gnueabihf/perl-base /usr/lib/arm-linux-gnueabihf/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/perl5/                                                                                                          Debconf/Config.pm line 173.

Message from syslogd@compteur at May 18 18:37:32 ...
 kernel:[  422.846993] EXT4-fs (mmcblk0p2): failed to convert unwritten extents to written extents -- potential data loss!  (inode                                                                                                           34935, error -30)

Message from syslogd@compteur at May 18 18:37:32 ...
 kernel:[  422.848706] EXT4-fs (mmcblk0p2): failed to convert unwritten extents to written extents -- potential data loss!  (inode                                                                                                           34935, error -30)

Message from syslogd@compteur at May 18 18:37:32 ...
 kernel:[  422.850817] EXT4-fs (mmcblk0p2): failed to convert unwritten extents to written extents -- potential data loss!  (inode                                                                                                           34935, error -30)
Warning: unable to close filehandle __ANONIO__ properly: Input/output error during global destruction.
dpkg: error: error opening configuration directory '/etc/dpkg/dpkg.cfg.d': Input/output error
E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (30: Read-only file system)
E: Failed to write temporary StateFile /var/lib/apt/extended_states
W: Could not open file '/var/log/apt/term.log' - OpenLog (30: Read-only file system)
E: Sub-process /usr/bin/dpkg returned an error code (2)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - pkgDPkgPM::Go (30: Read-only file system)
E: Problem executing scripts DPkg::Post-Invoke '/usr/bin/test -e /usr/share/dbus-1/system-services/org.freedesktop.PackageKit.serv                                                                                                          ice && /usr/bin/test -S /var/run/dbus/system_bus_socket && /usr/bin/gdbus call --system --dest org.freedesktop.PackageKit --object                                                                                                          -path /org/freedesktop/PackageKit --timeout 4 --method org.freedesktop.PackageKit.StateHasChanged cache-update > /dev/null; /bin/e                                                                                                          cho > /dev/null'
E: Sub-process returned an error code
E: Sub-process [ ! -f /usr/bin/snap ] || /usr/bin/snap advise-snap --from-apt 2>/dev/null || true returned an error code (100)
E: Failure running hook [ ! -f /usr/bin/snap ] || /usr/bin/snap advise-snap --from-apt 2>/dev/null || true
`

**Comment by MichaelGrafnetter** [comment]
@MichaelGrafnetter Yes, that seems like a corrupted Linux, maybe because of a bad SD card. But I was able to compile wmbusmeters with the same command sequence on a Raspberry Pi 3 with Raspbian bullseye.

**Comment by Marcus54542** [comment]
Ok thank you @MichaelGrafnetter 
I'll try to reformat the SD card, reinstall a new Linux and we'll see what happens...

**Comment by Marcus54542** [comment]
I reinstalled Debian GNU/Linux 12 (bookworm)"

I had to add the apt install libxml2-dev  command to get the full version
it works! I can read the reading of my meter and those of my neighbors.

great thank you @MichaelGrafnetter
