### ISSUE TITLE
Failed to start wmbusmerts.service

### ISSUE THREAD

**Issue by Marcus54542** [wmbusmeters/wmbusmeters#1278]
### Type of request

Question

### OS version

Debian GNU/Linux 12 (bookworm)

### wmbusmeters version

the last

### Your message goes here

Hello
The system is installed on a Raspberry Pi 3

I can read the value of my meters.
On the other hand, when launching the service I have this error
`sudo systemctl start wmbusmerts

Failed to start wmbusmerts.service: Unit wmbusmerts.service not found.

root@compteur:/# sudo systemctl status wmbusmeters

○ wmbusmeters.service - "wmbusmeters service"
     Loaded: loaded (/lib/systemd/system/wmbusmeters.service; disabled; preset: enabled)
     Active: inactive (dead)
       Docs: https://github.com/wmbusmeters/wmbusmeters
             man:wmbusmeters(1)
`

Did I forget something

Thank you

**Comment by volkerdeHaas** [comment]
same problem: Service is loaded on reboot but not activated. After manually starting the service things are running smoothly up to next reboot.

**Comment by Marcus54542** [comment]
try 
sudo systemctl enable wmbusmeters

**Comment by volkerdeHaas** [comment]
> try sudo systemctl enable wmbusmeters

You are my hero!!! So easy... I need to learn much more about Debian basics...
Thnx!

**Comment by pswiatki** [comment]
This belongs to  `systemd` fundamentals  :)
