### ISSUE TITLE
Reading kamstrup 303 heat meter

### ISSUE THREAD

**Issue by wverbiest** [wmbusmeters/wmbusmeters#1300]
### Type of request

Question

### OS version

Raspbian GNU/Linux 11 (bullseye)

### wmbusmeters version

wmbusmeters: 1.16.1-40-g73dd60d

### Your message goes here

I have compiled this version without errors, but after following the manual I am unable to contact the Kampstrup Multical 303 meter. I manage to request the meter via a small Python program and if I have the hex bytes edited via the https://wmbusmeters.org/ site, they are translated correctly. The bytes request I use to read the M-Bus meter are 0x10, 0x7b, 0x85, 0x00, 0x16 and this is the response: 
687a7a68088572337193822d2c40044310000004060d00000004143301000004ff077d00000004ff08720000000322ae1000332296000002594809025d170902613100022d0000122d5a00023b0000123b670502ff22000144060000000044140000000044ff070000000044ff0800000000522d0000523b0000426c0136a616
I use a USB to M-Bus adapter that is recognized as /dev/ttUSB0 and the baud rate is 2400.
My meter ID = 82937133

File: /etc/wmbusmeters.conf
loglevel=normal
# Remember to change auto here to the device you are going to use in production.
#device=auto:t1
device=MAIN=/dev/ttyUSB0:mbus:2400
logfile=/var/log/wmbusmeters/wmbusmeters.log
# Set to true to capture all received telegrams in log file.
logtelegrams=true
format=json
# Enable the meterfiles to write telegrams to disk.
#meterfiles=/var/lib/wmbusmeters/meter_readings
#meterfilesaction=overwrite
# Enable execution of a shell command for each received telegram. For example: curl or mqtt
#shell=/usr/bin/mosquitto_pub -h localhost -t wmbusmeters/ -m ""
#shell=psql water -c "insert into consumption values ('',,'') "
# The alarmshell is executed when a problem with the receiving radio hardware is detected.
#alarmshell=/usr/bin/mosquitto_pub -h localhost -t wmbusmeters_alarm -m " "
# The alarmtimeout and expected activity is also used to detect failing receiving radio hardware.
#alarmtimeout=1h
#alarmexpectedactivity=mon-sun(00-23)

File: /etc/wmbusmeters.d/MyKamstrup303
name=Kamstrup303
id=82937133
key=
driver=multical303
pollinterval=60s

wmbusmeters is running as a service
How can I read the meter every 300s?

**Comment by weetmuts** [comment]
From the README, change meter config as: 

pollinterval=300s
driver=multical303:MAIN:mbus
