### ISSUE TITLE
RTL dongle very hot

### ISSUE THREAD

**Issue by GDXFR** [wmbusmeters/wmbusmeters#1320]
### Type of request

Question

### HAOS version

2024.6.3

### wmbusmeters version

1.16.1

### Your message goes here

Hi, my RTL dongle (Nooelec NESDR) is very hot, is there any way to reduce usage and power it only a few minutes every hours? Thanks

**Comment by Tpaydt** [comment]
Which protocol are you using?  c1, s1, t1?

my RTL runs only with c1 but is still hot

**Comment by weetmuts** [comment]
I bought one because it looked so cute, but it heats up my laptop to a level where I stopped using it.
Even though the Noelec NSDR might withstand high heat, I am not sure my laptop does....

**Comment by weetmuts** [comment]
https://www.reddit.com/r/RTLSDR/comments/ng1zzt/nooelec_smartee_too_hot_with_solutionhopefully/

**Comment by weetmuts** [comment]
https://support.nooelec.com/hc/en-us/articles/360005889913-NESDR-Nano-Series
