### ISSUE TITLE
driver_qwater.cc HCA support

### ISSUE THREAD

**Issue by merbanan** [wmbusmeters/wmbusmeters#1324]
The following Q-walk_by telegrame can not be decoded.

https://wmbusmeters.org/analyze/4944934490130127350837ab780dff5f3500820200007e0007b06effcd6cff09000000ff2c510000001e3608000096070009000c000c00000001000000cdff0027d20000000000030005002f046d0d090f37955754 

Only this line seems to be missing to be able to decode the telegram.

di.addDetection(MANUFACTURER_QDS, 0x08, 0x35);

**Comment by weetmuts** [comment]
Thanks! However 0x08 means heat cost allocator and is QDS,0x08,0x35 is already registered on the qcaloric HCA driver.

I think this is the normal qcaloric proprietary telegram that no-one has attempted to decode yet.
The qcaloric also sends mbus compliant telegrams, however not so often.
