### ISSUE TITLE
Only a few meters related to me

### ISSUE THREAD

**Issue by comod** [wmbusmeters/wmbusmeters#1343]
### Type of request

Question

### OS version

Linux

### wmbusmeters version

0

### Your message goes here

More a general question:

I am on my very first steps with this topic. I logged a few messages with auto:c1,t1 and only got 1 of 6 Heat cost allocation meter telegrams related to me.
Is there any other option i should try? How likely is it that 5 devices do not send anything? One of them is 3 meters away and the one from where ive got messages is 5 meters away.
What can i do?

There was only one other message for warm water which was mine, but encrypted. Is there a guide to decrypt those?

**Comment by Tpaydt** [comment]
Which HCA model do you have?
Depending on the model and settings, some models switch off data transmission after a certain time.
