### ISSUE TITLE
(apator162) telegram contains a register (79) with unknown size.

### ISSUE THREAD

**Issue by mellaiz** [wmbusmeters/wmbusmeters#1358]
### Type of request

Bug

### HAOS version

13.1

### wmbusmeters version

1.17.1

### Your message goes here

Hi.

I am reporting telegram message which seems to be faulty?
5E4401061202960405077A790050852F2F0F78A599983B0200435000805771165771160103000010653A00007919321E0000620000006200000000000000000000000000000000000000000000000000000000000000A0422C6004FFFF2FBF

<img width="2301" alt="Screenshot 2024-09-05 at 22 02 23" src="https://github.com/user-attachments/assets/b443862b-80d8-469d-b7cb-fa69dcf9c5dd">
<img width="1002" alt="Screenshot 2024-09-05 at 22 02 49" src="https://github.com/user-attachments/assets/a6357d19-25e9-471b-ac3b-76f2ba616bd7">

**Comment by weetmuts** [comment]
Many thanks! I improved the apator162 driver to handle that field as well. It stores historical data.
If someone has the time, we could now also extract the historical data.
