### ISSUE TITLE
Driver not compiled / created pollucomf.json

### ISSUE THREAD

**Issue by faulesocke85** [wmbusmeters/wmbusmeters#1380]
### Type of request

Bug

### HAOS version

13.1

### wmbusmeters version

1.17.1

### Your message goes here

Hi there, as I read in the documentation there is a driver for pollucom heat meters. It seems the needed driver ist not created even there seems to be a source file. My log shows this: 

[23:51:49] INFO:   File /config/wmbusmeters/etc/mqtt_discovery/pollucomf.json not found. 

And the folder contains only that files: 
<img width="825" alt="Bildschirmfoto 2024-10-05 um 00 12 30" src="https://github.com/user-attachments/assets/dba3b5e1-42b4-45b7-9bc2-11e90e66f49f">

I am using mbus not wmbus. 

There is another user with the problem found something in mqttdiscover.sh 
https://github.com/wmbusmeters/wmbusmeters/issues/711

I am not able to implement this. Can you please check this? 

My config: 

#wmbusmeters.conf
device=MAIN=/Dev/ttyUSB0:mbus:2400 
##rest is standard 

#meter-0001 
an in my meter 
driver=pollucomf:MAIN:mbus
id=123xxxyxyxyyyyyyy
key=NOKEY
name=WMZ1
pollinterval=60s

BR

**Comment by BIBOLV** [comment]
Hi,
You can check driver definitions that has been added [here](https://github.com/wmbusmeters/wmbusmeters-ha-addon/tree/main/wmbusmeters-ha-addon-edge/mqtt_discovery). You can create [PR](https://github.com/wmbusmeters/wmbusmeters-ha-addon/blob/main/CONTRIBUTING.md) for driver you are interested in or describe them manually in HA sensors.

**Comment by faulesocke85** [comment]
Solved
