### ISSUE TITLE
Addon refuses to start after Update to [edge] 1.17.1-27-1

### ISSUE THREAD

**Issue by cosgrove39264** [wmbusmeters/wmbusmeters#1384]
### Type of request

Bug

### HAOS version

13.2.rc1

### wmbusmeters version

1.17.1-27-1

### Your message goes here

The add-on container stops when /data/drivers/ contains no files.

<code>cp: can't stat '/data/drivers/*': No such file or directory
</code>

If I create a dummy file in /data/drivers, the container starts until wmbusmeters tries to load the dummy-file as a driver.

I think changing the line 43 in run.sh 
from 
<code>cp /data/drivers/* ${CONFIG_DATA_PATH}/etc/wmbusmeters.drivers.d/
</code>
to
<code>cp /data/drivers/* ${CONFIG_DATA_PATH}/etc/wmbusmeters.drivers.d/ || true
</code>
should resolve the problem.

**Comment by weetmuts** [comment]
You are right. Fix pushed please test.
