### ISSUE TITLE
Improve the process of installing the HA addon. Perhaps build docker image in CI?

### ISSUE THREAD

**Issue by pawsli** [wmbusmeters/wmbusmeters#334]
Hello!
I've tried to install wmbusmmeters HA addon but I can not do this. 
 I received error like this:
 ![a](https://user-images.githubusercontent.com/64145636/132256733-54dd6c6c-21af-43d0-ae15-e19db0048aed.jpg)
English translation of polish text on screenshot is: "The add-on could not be installed" ;)

These are supervisor log screenshots:

![b](https://user-images.githubusercontent.com/64145636/132256797-fcaffaf4-a172-4703-8a1c-82961de270a7.jpg)

![c](https://user-images.githubusercontent.com/64145636/132256781-21770cfd-6d9c-4e53-a486-4e98b737e7cf.jpg)

And error details:
![e](https://user-images.githubusercontent.com/64145636/132258887-3513e5be-450d-4110-b0bc-7bbb1a7acc87.jpg)

And this is my system tab screenshot:
![d](https://user-images.githubusercontent.com/64145636/132256912-77f1e7b1-f416-4cb6-ae84-c5dfccb168e3.jpg)

**Comment by weetmuts** [comment]
Ping @to-masz @andriej

**Comment by to-masz** [comment]
@pawsli do you run supervisor on pure debian 10? I will see if that can be related to HA core 2021-9

**Comment by to-masz** [comment]
@pawsli from quick research on the Internet - you need to update your docker version on the host machine (running Debian 10) 😉 

@weetmuts @BIBOLV today HA owners build the addon image on their machines. Would it be possible to build it in the project CI? The only complexity is that there is an official builder https://github.com/home-assistant/builder and either we should use it or figure out what it does additionally to normal docker build action

**Comment by pawsli** [comment]
> @pawsli do you run supervisor on pure debian 10? I will see if that can be related to HA core 2021-9

My host machine is running OMV 5.3.9-1 (Usul).

Thanks for the tip with the docker update. I'll check it in a few days because now I don't have direct access to the host machine.

**Comment by andriej** [comment]
@pawsli just remember that non-Debian non-stable installation are out of support regarding Supervisor, so even if it would end that it's fault of Supervisor somehow, you won't get any support from HA's devs side. It might not matter, but it's worth to remember.

**Comment by BIBOLV** [comment]
@to-masz, sure docker images can be built using CI. Preferably in github using actions, so should I create it or will you? I did a quick view of your docker file and currently I do not think that it could be combined in one, so better to build separate one for ha-addon and if it will make sense, then we will look at it later on.

**Comment by weetmuts** [comment]
@to-masz When the HA addon user has installed the addon (and it built the source automatically)
will it stick to that built version until the user asks for an upgrade?

**Comment by to-masz** [comment]
@weetmuts in general yes. 

When the `version` value will be increased in `ha-addon/config.json` all add-on users will see the update option. Once approved, the HA supervisor will download the new config (and as long as there is no `image` with docker url there - the HA supervisor will build the Dockerfile on its own; if image url is provided - it will just pull the image instead).

**Comment by Adman** [comment]
@jsuchal Could you please give a hint on how to build that docker image? I tried running `docker build` in ha-addon folder, but it requires `BUILD_FROM` argument and I'm not sure what to pass there. Thanks!

**Comment by BIBOLV** [comment]
HA add-on has moved to separate repo - https://github.com/wmbusmeters/wmbusmeters-ha-addon
It has now pre-built container images and config interface changes - please test and close this issue if no other questions.
