### ISSUE TITLE
Apator heat alocator

### ISSUE THREAD

**Issue by Santa77** [wmbusmeters/wmbusmeters#373]
New APATOR heat alocator seen....

Telegram data:
18440186729616360708a02100592b000000000000000000002f17dc3b
18440186359616360708a02100592b0000df02df025d000a007817dc3b
18440186799616360708a02100592b00002401f30246000600cd16e15e

 Can anyone look at it please?

**Comment by weetmuts** [comment]
@Santa77 Any update? Collect telegrams and at the same telegram read the values displayed on the
meter so that we can correlate the telegram to the values.

**Comment by Santa77** [comment]
I did not drive same route since then, i have planed to travel same route next month...

**Comment by kedar-1** [comment]
Hello,

I have probably the same type of HCA by Apator - Metra - EITN 30.6
Grabbed from spec sheet:

Data sent by the cost allocator via the radio module
_– Serial number of cost allocator_
_– Start date of accounting period_
_– Reading date_
_– Electronic seal breakage date_
_– Measurement of current accounting period of one year_
_– Measurement of previous accounting period of one year_
Additional data sent only by the 30.51 heat meter:
_– Mean temperature in the previous billing year_
_– Mean temperature in the current billing year_
Additional data sent only by the **30.6** heat meter
_– Measurement of current accounting period of one month_
_– Measurement of previous accounting period of one month_
_– Average ambient temperature of radiator for previous accounting period of one month__

Telegrams:
18440186276921360708a02100442d00000000000000000000a517dc3b
18440186225121360708a02100442d000000000000000000009517dc3b
18440186286921360708a02100442d000000000000000000004717dc3b
  
  As these HCAs were installed last week all meters are still 0 - except the date of course
  During the next months I'll try to monitor telegrams for metering changes.
  
  If there is a way how to improve or create a driver I'll be ready to help..
