### ISSUE TITLE
Claim multical403 is the correct driver when multical603 more correct

### ISSUE THREAD

**Issue by petterreinholdtsen** [wmbusmeters/wmbusmeters#459]
I have successfully converted my .zip.kem file to a wmbusmeters.d, and get some values from my meters.  But when I start it up, it complain that the correct type should be multical403 and not multical603, while only using multical603 will give me a non-zero value for total_energy_consumption_kwh.

Here is an example run and output:

```
./build/wmbusmeters --useconfig=/home/pere/.config/wmbusmeters/ --device=rtlwmbus
Started config rtlwmbus[00000003] listening on none
(meter) 71054899: meter detection did not match the selected driver multical603! correct driver is: multical403
(meter) Not printing this warning again for id: 71054899 mfct: (KAM) Kamstrup Energi (0x2c2d) type: Heat volume at inlet meter (0x0c) ver: 0x34
{"media":"heat volume at inlet","meter":"multical603","name":"71054899","id":"71054899","total_energy_consumption_kwh":32175,"total_volume_m3":3591.16,"volume_flow_m3h":0,"t1_temperature_c":31.45,"t2_temperature_c":35.79,"at_date":"2022-01-31 00:00","current_status":"","energy_forward_kwh":153189,"energy_returned_kwh":124887,"timestamp":"2022-01-31T15:05:00Z","device":"rtlwmbus[00000003]","rssi_dbm":140}
[...]
```

Perhaps some detection logic should be adjusted?

**Comment by weetmuts** [comment]
Can you post a logtelegrams=true output here:
ie telegram=|.....|

Do you have a multical603 meter?

**Comment by petterreinholdtsen** [comment]
[Fredrik Öhrström]
> Can you post a logtelegrams=true output here:
> ie telegram=|.....|

I'm not quite sure how to enable this.  Tried adding it to my
~/.config/wmbusmeters/etc/wmbusmeters.conf but got no such dump.

> Do you have a multical603 meter?

My meter modell is 403WD0244 according to the front of the meter, but
using the multical403 driver did not give me the number I needed.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by weetmuts** [comment]
You could run it from the command line just to get a couple of logged telegrams.
wmbusmeters --logtelegrams rtlwmbus:c1,t1 MyMeter multical403 71054899 <yourkey>

**Comment by petterreinholdtsen** [comment]
[Fredrik Öhrström]
> You could run it from the command line just to get a couple of logged telegrams.
> wmbusmeters --logtelegrams rtlwmbus:c1,t1 MyMeter multical403 71054899
> <yourkey>

OK.  Here are three telegrams.

% build/wmbusmeters --logtelegrams  --format=json auto Heat multical603 71054899 <redacted>
Started auto rtlwmbus[00000003] listening on none
(meter) Heat: meter detection did not match the selected driver multical603! correct driver is: multical403
(meter) Not printing this warning again for id: 71054899 mfct: (KAM) Kamstrup Energi (0x2c2d) type: Heat volume at inlet meter (0x0c) ver: 0x34
telegram=|56442D2C99480571340C8D2019708C8322C88F78|0406AF7D000004FF076556020004FF08D7E701000414CC7A0500043B0000000002598F0C025D920D04FF2200000000026CDF214406AF7D00004414CC7A0500426CC121|+6
{"media":"heat volume at inlet","meter":"multical603","name":"Heat","id":"71054899","total_energy_consumption_kwh":32175,"total_volume_m3":3591.16,"volume_flow_m3h":0,"t1_temperature_c":32.15,"t2_temperature_c":34.74,"at_date":"2022-01-31 00:00","current_status":"","energy_forward_kwh":153189,"energy_returned_kwh":124887,"timestamp":"2022-01-31T16:02:29Z","device":"rtlwmbus[00000003]","rssi_dbm":138}
telegram=|3F442D2C99480571340C8D201A718C8322BE3D794DB3E88D|AF7D000065560200D7E70100CC7A050000000000810C930D00000000DF21AF7D0000CC7A0500C121|+23
{"media":"heat volume at inlet","meter":"multical603","name":"Heat","id":"71054899","total_energy_consumption_kwh":32175,"total_volume_m3":3591.16,"volume_flow_m3h":0,"t1_temperature_c":32.01,"t2_temperature_c":34.75,"at_date":"2022-01-31 00:00","current_status":"","energy_forward_kwh":153189,"energy_returned_kwh":124887,"timestamp":"2022-01-31T16:02:46Z","device":"rtlwmbus[00000003]","rssi_dbm":139}
telegram=|3F442D2C99480571340C8D201B728C8322BE3D794DB3E88D|AF7D000065560200D7E70100CC7A050000000000810C930D00000000DF21AF7D0000CC7A0500C121|+39
{"media":"heat volume at inlet","meter":"multical603","name":"Heat","id":"71054899","total_energy_consumption_kwh":32175,"total_volume_m3":3591.16,"volume_flow_m3h":0,"t1_temperature_c":32.01,"t2_temperature_c":34.75,"at_date":"2022-01-31 00:00","current_status":"","energy_forward_kwh":153189,"energy_returned_kwh":124887,"timestamp":"2022-01-31T16:03:02Z","device":"rtlwmbus[00000003]","rssi_dbm":140}
^C
%

--
Happy hacking
Petter Reinholdtsen

**Comment by weetmuts** [comment]
Hi! Thanks for reporting. You are quite right, the multical403 603 etc are very similar meters and for historical reasons they accidently got their own drivers. Can you try out your telegrams here: https://wmbusmeters.org
(Use the long telegrams on the web, since the short are compressed and can only be decoded if wmbusmeters has seen a long before.)

It seems like all the drivers multical302 to multical803 can be replaced with one single driver.
It would be good if this replacement driver could be written using the new driver_xxx.cc
format which is much easier to maintain. I will also add the PrintPropert::OPTIONAL which will indicate that the json field should not be printed if no value was found in the telegram.)

So, please analyze your telegrams and force different drivers using the driver selection box, 
and confirm if you believe the drivers all overlap enough to warrant a single driver.

**Comment by petterreinholdtsen** [comment]
[Fredrik Öhrström]
> Hi! Thanks for reporting. You are quite right, the multical403 603 etc
> are very similar meters and for historical reasons they accidently got
> their own drivers. Can you try out your telegrams here:
> https://wmbusmeters.org

> (Use the long telegrams on the web, since the short are compressed and
> can only be decoded if wmbusmeters has seen a long before.)

I am not sure how to identify if the telegram strings I posted earlier
are in the long or short format, nor how to get long formats out if they
were short.  Can you provide a recipe?

The <URL: https://wmbusmeters.org > service seem to require that I share
my meters secret key, which seem like a bad privacty practice.  Any
other alternative?

> It would be good if this replacement driver could be written using the
> new driver_xxx.cc format which is much easier to maintain. I will also
> add the PrintPropert::OPTIONAL which will indicate that the json field
> should not be printed if no value was found in the telegram.)

I am not convinced I am competent to rewrite these into one single
driver.

> So, please analyze your telegrams and force different drivers using
> the driver selection box, and confirm if you believe the drivers all
> overlap enough to warrant a single driver.

I can try to parse various telegrams to see what I get, once I know how
to get the required telegram format and how to do it locally.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by weetmuts** [comment]
Long/short is just the number of bytes:
Here is a short, as you can see it fails to decode after format signature since it has not seen the signature before:

https://wmbusmeters.org/analyze/3F442D2C99480571340C8D201B728C8322BE3D794DB3E88DAF7D000065560200D7E70100CC7A050000000000810C930D00000000DF21AF7D0000CC7A0500C121

Here is a long one:
https://wmbusmeters.org/analyze/56442D2C99480571340C8D2019708C8322C88F780406AF7D000004FF076556020004FF08D7E701000414CC7A0500043B0000000002598F0C025D920D04FF2200000000026CDF214406AF7D00004414CC7A0500426CC121

**Comment by weetmuts** [comment]
>The <URL: https://wmbusmeters.org/ > service seem to require that I share
>my meters secret key, which seem like a bad privacty practice.  Any
>other alternative?

You can paste your already decrypted telegrams, that you already posted in this github issue. :-) Which are the ones I created links for above.

You can always run wmbusmeters --analyze=<key> <encrypted_telegram> 
from your command line.

**Comment by weetmuts** [comment]
> I am not convinced I am competent to rewrite these into one single driver.

No worries, I will do the rewriting after I get your input.

**Comment by petterreinholdtsen** [comment]
Hm, my email from 2022-03-28 seem to have not made it into github.  This is what I wrote:

Not quite sure what kind of messages you want, but taking the message
you already posted, I see this difference in the JSON output for the two
drivers multical403 and multical603:

--- multical403.json    2022-03-28 19:42:30.440001900 +0200
+++ multical603.json    2022-03-28 19:43:09.600324151 +0200
@@ -1,14 +1,16 @@
 {
     "media":"heat volume at inlet",
-    "meter":"multical403",
+    "meter":"multical603",
     "name":"",
     "id":"71054899",
-    "total_energy_consumption_kwh":0,
+    "total_energy_consumption_kwh":32175,
     "total_volume_m3":3591.16,
     "volume_flow_m3h":0,
     "t1_temperature_c":32.15,
     "t2_temperature_c":34.74,
     "at_date":"2022-01-31 00:00",
     "current_status":"",
-    "timestamp":"2022-03-28T17:42:11Z"
+    "energy_forward_kwh":153189,
+    "energy_returned_kwh":124887,
+    "timestamp":"2022-03-28T17:42:50Z"
 }

What more will more telegrams bring to the table?  Is the different
values and timestamps the difference?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[github-actions[bot]]
> This issue is stale because it has been open for 2 month with no
> activity. Remove stale label or comment or this will be closed in 1
> month.

Do you need more from me here?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by weetmuts** [comment]
Ah, I think this one is solved already! All the multical heat meters have been merged into a single driver kamheat. The old driver names alias to kamheat, so they still work.

Please check using analyze if your telegrams contain anything that is not properly decoded!

The wmbusmeters.org analyze links above look good anyway!

**Comment by petterreinholdtsen** [comment]
[Fredrik Öhrström]
> Please check using analyze if your telegrams contain anything that is
> not properly decoded!

I did not check this, but I had a look at the json submitted to my MQTT
broker and the information look good with the new version. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by weetmuts** [comment]
Great! Good to hear!
