### ISSUE TITLE
No MQTT-Message at HomeAssistant SuperVisor

### ISSUE THREAD

**Issue by SWAT9119** [wmbusmeters/wmbusmeters#483]
I have an Home-Assistant SuperVisor Installation (in Docker) which contains an MQTT-Server.

With an MQTT-Explorer I can see the messages, homeassistant and the core-messages can be seen.

But I don´t get messages from wmbusmeters.

The Log says:

`(shell) exec "/bin/sh"
(shell) arg "-c"
(shell) arg "/usr/bin/mosquitto_pub -h 192.168.178.10 -t wmbusmeters/"$METER_ID" -m "$METER_JSON""
(shell) env "METER_JSON={"media":"warm water","meter":"waterstarm","name":"EG_Warmwasser_Kueche","id":"22029791","meter_timestamp":"2022-02-23 12:34","total_m3":0.185,"total_ba>
(shell) env "METER_ID=22029791"
(shell) env "METER_NAME=EG_Warmwasser_Kueche"
(shell) env "METER_MEDIA=warm water"
(shell) env "METER_TYPE=waterstarm"
(shell) env "METER_TIMESTAMP=2022-02-23T11:35:36Z"
(shell) env "METER_TIMESTAMP_UTC=2022-02-23T11:35:36Z"
(shell) env "METER_TIMESTAMP_UT=1645616136"
(shell) env "METER_TIMESTAMP_LT=2022-02-23 12:35.36"
(shell) env "METER_DEVICE=im871a[00103071]"
(shell) env "METER_RSSI_DBM=-80"
(shell) env "METER_METER_TIMESTAMP=2022-02-23 12:34"
(shell) env "METER_TOTAL_M3=0.185"
(shell) env "METER_TOTAL_BACKWARDS_M3=0"
(shell) env "METER_CURRENT_STATUS=OK"
(shell) env "METER_METER_VERSION=000008"
(shell) env "METER_PARAMETER_SET=1100"
(shell) waiting for child 5606 to complete.
(shell) /bin/sh: return code 0
`

The child number is counting up

What´s wrong?

**Comment by BIBOLV** [comment]
Were you able to sort out this issue? Can it be closed?
