### ISSUE TITLE
FR: posibility to set retain flag in ha-addon

### ISSUE THREAD

**Issue by dzikus** [wmbusmeters/wmbusmeters#484]
Feature request: Please set "-r" in 'ha-addon/run.sh' or give such option from addon configuration site.

Change
/usr/bin/mosquitto_pub ${pub_args[@]} -t \$TOPIC -m "\$MESSAGE"
into
/usr/bin/mosquitto_pub ${pub_args[@]} -r -t \$TOPIC -m "\$MESSAGE"

**Comment by weetmuts** [comment]
Thanks for the suggestion! But can you provide a pull request? I am not an expert on the ha-addon. @to-masz

**Comment by BIBOLV** [comment]
Closing this as clone for https://github.com/wmbusmeters/wmbusmeters/issues/350
