### ISSUE TITLE
No possible to change shell in ha-addon configuration site

### ISSUE THREAD

**Issue by dzikus** [wmbusmeters/wmbusmeters#485]
If you want to change shell command to something more complicated than orig line you will get such strange formatting with useless wmbusmeters inside container:

For example I want to set my own mosquitto_pub with retain flag, so I'm changing shell line to:
`shell=/usr/bin/mosquitto_pub -h 10.0.0.1 -p 1883 -t wmbusmeters/12345678 -m "$METER_JSON"
`

<img width="1020" alt="1" src="https://user-images.githubusercontent.com/3209066/155718103-70e97ba6-c8ae-41ca-9d2f-10d7b099d527.png">

but after hitting "Save":

<img width="1023" alt="2" src="https://user-images.githubusercontent.com/3209066/155718134-f19e1415-b1b9-47c2-9a99-8d5a4378cd87.png">

**Comment by to-masz** [comment]
@dzikus I believe this is related to the yaml formatting applied by home assistant ... but it does not change a fact it should work - what issue do you have?

**Comment by rincewindy** [comment]
The formatting seems to go wonky any time a non-standard shell command is used, e.g. 
![image](https://user-images.githubusercontent.com/97702737/168624228-663cf073-b839-4178-baef-2fee3021ac24.png)
vs
![image](https://user-images.githubusercontent.com/97702737/168624721-ac0a9764-8999-4234-af22-d808b7390ce4.png)
It does work, but sub-optimal.

**Comment by BIBOLV** [comment]
HA add-on has moved to separate repo - https://github.com/wmbusmeters/wmbusmeters-ha-addon
It has now pre-built container images and config interface changes - please test and close this issue if no other questions.
