### ISSUE TITLE
Configuration from HA Integration

### ISSUE THREAD

**Issue by Kosygor** [wmbusmeters/wmbusmeters#535]
Hello
I was playing with wmbusmeters integration and had noticed that both configuration and meters are not interpreted properly until I had manually added newline character `\n`. Without that everything is one line and wmbusmeters is throwing errors to log.

**Comment by BIBOLV** [comment]
HA add-on has moved to separate repo - https://github.com/wmbusmeters/wmbusmeters-ha-addon
It has now pre-built container images and config interface changes - please test and close this issue if no other questions.
