### ISSUE TITLE
ha-addon not working in HA OS Virtualbox

### ISSUE THREAD

**Issue by softeg-klee** [wmbusmeters/wmbusmeters#538]
Hello,

Thanks to integrate this tool into HA.

I have a issue when at the step 03 i try to install the addon 
Following the instructions in Docs.md for adding the repository
https://github.com/weetmuts/wmbusmeters/blob/master/ha-addon/DOCS.md 
in the supervisor , this appears

![Settings-–-Home-Assistant](https://user-images.githubusercontent.com/51447008/167276890-42fe1619-d17a-4499-8ca2-04680e69dcb4.png)

system log shows

Failed to to call /addons/cada3e3b_wmbusmeters/info - Addon cada3e3b_wmbusmeters does not exist

Thanks for reply.

**Comment by jaco** [comment]
Same problem here. I have switched from rpi to virtualbox and when I tried to start addon, I have got:

```
Failed to to call /addons/cada3e3b_wmbusmeters/info - Addon cada3e3b_wmbusmeters does not exist
```

I have tried reinstall form gui and cli, same results:

```
$ ha addons install cada3e3b_wmbusmeters
Processing... Done.
Error: The command '/bin/ash -o pipefail -c make' returned a non-zero code: 2
```
