### ISSUE TITLE
Techem Radio4 meters for cold & warm water /  Techem vario 4.1.1  (heat meter) decoding

### ISSUE THREAD

**Issue by thisandre** [wmbusmeters/wmbusmeters#672]
We are using these meters in or house (all data is encrypted but I got the keys from Techem)
I made following observations:
- Warm and cold meters are looking the same (Both marked as Techem-Radio4), but the JSON decoding for cold water indicates the meter as Weh_07, as the warm water meter decodes as "warm water - driver not found". 
Question: Which driver / meter to use??
- The Techem Vario 4.1.1 is indicated as "heat", which is correct, but does not find a driver.
Same question: which driver to use??
According to the public available info about these meters, the information that should be available is the consumption of the previous period and the previousdate.  
The heat consumption is recorded in the telegram as "4406", followed by 4 bytes of consumption value (in kWh). 
For the watermeters, the consumption is recorded as "4315", followed by 3 bytes of consumption value (in m3/10). 
For all meters, the previous period is indicated as "426", followed by 2 bytes with the date.  
All other data in the telegrams is manufacturer specific and obviously hidden with a key.  (see attached file with the telegram details)
Do I have to write a new driver for these meters, or is there one which I can use? 

[logtel1.txt](https://github.com/weetmuts/wmbusmeters/files/10031652/logtel1.txt)

**Comment by MartinBachmannHD** [comment]
...as I am struggling with Techem as well - may I ask which hardware and which protocol you are using? I used the CUL with 'T' and that was somehow unsuccessful with radio 4 / vario 4...

**Comment by thisandre** [comment]
I'm using just a simple DVB-T/FM/DAB USB stick (820T2 & SDR) with rtlwmbus.   With this I can receive all meters from 1 floor down and 1 floor up in the house.

**Comment by BIBOLV** [comment]
Try mkradio4
```
{
    "media":"heat",
    "meter":"mkradio4",
    "name":"",
    "id":"67627875",
    "total_m3":4902.9,
    "target_m3":2.5,
    "timestamp":"2022-11-18T22:26:53Z"
}
```

**Comment by thisandre** [comment]
I tried already near all drivers!  The "total_m3" and "target_m3" don't match. Neither is the previous date indicated. 
The only values that are available in this message (apart from the "vendor secrets") are the previous consumption time and previous consumption m3, as I described in the issue. 
I'm intended to create a driver for this but I'm struggling with the set-up.  According to the instructions, one should create a file called "driver_xxx.cc" but in the src directory, lots of "meter_xxx.cc" files also exist.  Do we need both, or can everything be put together in de driver_xxx.cc file??

**Comment by BIBOLV** [comment]
"driver_xxx.cc" is correct one, "meter_xxx.cc" are old standard files left that are being refactored to new style.

**Comment by thisandre** [comment]
The driver for Techem Vario451mid is using the same codes, with a different interpretation of the data fields as the Techem Vario411. (both using 0x04 / 0x17 in di.addDetection). How can we differentiate between the 2 devices and send corresponding JSON messages?

**Comment by BIBOLV** [comment]
Diver differentiates message using manufacturer, media type and media version. Could you please specify where do you see overlap - I did a quick search and could not find any. For 67627875 meter detection line would be:
```
di.addDetection(MANUFACTURER_TCH, 0x04,  0x28);
```

**Comment by thisandre** [comment]
Sorry, my mistake, I was working on an elderly version, where the file "meter_detection.h" was still there and claimed the media type & version for the vario451mid. This file seems to be gone in the actual version.

**Comment by hemonu** [comment]
Look's like I have the same combination of meter manufacturers and "Techem Radio4" as thisandre. How did you get the AES key from Techem?

**Comment by thisandre** [comment]
Just asked Techem and got them after a long procedure of safety aspects (mails with separated passwords etc.). I also had to sign that I would not disclose the keys to third parties.  I'm doing the "Hausverwaltung" in our house myself and we rent the meters from Techem. I needed the info to do my job. I also asked them for a technical description of the telegram format describing the manufacturer specific information.  Let's see what comes out ...

**Comment by MartinBachmannHD** [comment]
I contacted Techem via the contact page on their public website a few days ago - but without success until now. But I am not a direct customer of Techem, only indirectly via our 'Hausverwaltung'. Is there a special page / special email to better get in contact with Techem about the keys? Ideally it would be a self-service... :-)

**Comment by BIBOLV** [comment]
@thisandre - how tests are progressing?

**Comment by k1tfh** [comment]
@thisandre  - i got 2 keys from techem. which one should i use? one labeled "Keys A" and the other "Key S".

**Comment by k1tfh** [comment]
I am confused. I checked some of your telegrams in your logtel1.txt with [https://wmbusmeters.org](url) without any Decryption key. 

This is what comes out: 

Auto driver  : mkradio4a
Best driver  : topaseskr 05/47
Using driver : mkradio4a 00/00

{
    "media":"warm water",
    "meter":"mkradio4a",
    "name":"",
    "id":"66953825",
    "target_m3":16.1,
    "target_date":"2021-12-31",
    "timestamp":"2023-11-21T21:50:21Z"
}

So how did you manage to collect such large numbers of telegrams? It seems like the meters from techem are both encrypted and decrypted. Using no key or the key from techem leading to a block.

**Comment by thisandre** [comment]
I don't know what meters you're using, but in my case, I was not able to read the data without decoding.  Logtel1.txt is already decoded by the wmbus program using the "Keys A" data for that specific meter (identified with the Id).  As I mentioned, I was not able to decode the rest of the message, only the part giving the end-of-year values. In my case, the encryption key is meter specific, meaning I need a key for every meter (Which I got from Techem). I don't know whether Techem is using other setups for other properties (as common keys for the property, keys per floor, or something like that). In my case, I'm collecting data from over 30 meters which are definitely not readable without the keys!

**Comment by k1tfh** [comment]
Perhaps this could help: [https://github.com/wmbusmeters/wmbusmeters/issues/1102#issuecomment-1823358611](url)

I now receive the current values with a delay of a few seconds to a few minutes. That's enough for me in combination with Home Assistant. I still get a few error messages, but the values are coming in. I hope it stays that way.

**Comment by thisandre** [comment]
Glad that you made it!  It is correct that the devices send out the info roughly at some minutes interval.
It however does not solve the problem of decoding the 'proprietary part' of the message, which should disclose the current consumption and other info. As I said, I already tried various combinations of aes-keys and message lengths but did not get any further as getting the yearly values.

**Comment by fhb** [comment]
I'm living in a rental and am trying to get the keys for my water and heat counters. I just sent an email to service@techem.de requesting the keys providing all the information from my end of year bill. I'll report back wether they refuse my request or provide the keys.

@k1tfh re you also a direct customer of techem? 
@MartinBachmannHD did you get the keys?

**Comment by fhb** [comment]
So they won't give the keys to a third party:

> vielen Dank für Ihre Anfrage vom 15. Dezember 2023.
> 
> Bitte haben Sie Verständnis, dass wir die von Ihnen gewünschten Informationen nur unserem Vertragspartner zur Verfügung stellen können.
> 
> Bitte wenden Sie sich an Ihre Hausverwaltung.
> 
> Diese kann die OMS Schlüssel gerne bei uns anfordern.

**Comment by PetrStepka** [comment]
> [@thisandre](https://github.com/thisandre) - i got 2 keys from techem. which one should i use? one labeled "Keys A" and the other "Key S".

Quick question: when Techem provide WM-Bus encryption keys for meters, are those keys unique to each meter/serial number, or is there a common/shared key used across multiple devices/models?

**Comment by MartinixH** [comment]
> > [@thisandre](https://github.com/thisandre) - i got 2 keys from techem. which one should i use? one labeled "Keys A" and the other "Key S".
> 
> Quick question: when Techem provide WM-Bus encryption keys for meters, are those keys unique to each meter/serial number, or is there a common/shared key used across multiple devices/models?

According to your name, you are Czech. Did you received keys from Czech Techem? I wrote to them several months ago and did not receive any response.

**Comment by thisandre** [comment]
The keys are unique for every single meter. When I remember correctly,  one should use the A Keys.  I did not figure out the use of the S key.  
The key only provides you the possibility to decode the 'common part' of the message, which gives you the value of the meter on Dec 31th of the previous year and that date.  I was not able to decode the rest of the message, since this is 'manufacturer specific' according to the standards. Techem Germay did not answer to my question to provide the decoding information for that part, even when I offered them to sign an NDA agreement. The experience Martinix had with sending questions to Techem is exactly the same I had. I'm waiting for a response since  the 2nd of June 2024 ...

**Comment by thisandre** [comment]
Apparently, a private person does not get the keys.  I was able to ask for them since I'm registered at Techem as 'Hausverwaltung' (Property management).

**Comment by MartinixH** [comment]
I asked them as chairman of the homeowners association and I did not received even rejection

**Comment by PetrStepka** [comment]
> > > [@thisandre](https://github.com/thisandre) - i got 2 keys from techem. which one should i use? one labeled "Keys A" and the other "Key S".
> > 
> > 
> > Quick question: when Techem provide WM-Bus encryption keys for meters, are those keys unique to each meter/serial number, or is there a common/shared key used across multiple devices/models?
> 
> According to your name, you are Czech. Did you received keys from Czech Techem? I wrote to them several months ago and did not receive any response.

I contacted service@techem.de asking if they could provide the WM-Bus decryption keys for my own water meter.
Today I got the following response:

`
Good day,
 
Thank you for your message to Techem.
 
In order to be able to provide you with information, we still need your property or customer number. This is the only way we can process your request as quickly as possible.
 
Alternatively, you can also give us the complete address of the property.
`

So it seems they’re willing to cooperate, but they require either the customer/property number or the full address to verify ownership before they share anything.

I’ve just sent them my full address and will update here once they reply again.

**Comment by thisandre** [comment]
It seems to forward towards the right direction! I believe their main  concern is data security and the proof of identity.  Can you ask them also for the layout of the manufacturer part of the message and how to read or decode this ? This is where I did not get an answer.

**Comment by jsuchal** [comment]
@PetrStepka this looks pretty good! Could you share the request text template & how long it took to respond?

**Comment by Nopel2020** [comment]
Hello @PetrStepka!

Did you get a response from Techem? I am in the same situation, trying to get my keys from Techem here in Belgium. So far no response.
