### ISSUE TITLE
Kamstrup Multical 303 in T1?

### ISSUE THREAD

**Issue by PieterKruithof** [wmbusmeters/wmbusmeters#686]
Hi,

I've mounted a Multical 303 to my heat pump. Even though this heat meter is not listed here, it is working with wmbusmeters. With a im871a I have been able to read the C1 message and pass it through via MQTT.

I have seen that it is maybe possible to also read the T1 messages?  In the config I use: `device=/dev/ttyUSB0:im871a:t1`
As a result in the logs `Started config im871a[00103812] on /dev/ttyUSB0 listening on t1`
But still all I get is a C1 message like:
`{"media":"heat","meter":"multical302","name":"Warmtepomp","id":"82813005","total_energy_consumption_kwh":1311.6,"current_power_consumption_kw":0,"total_volume_m3":592.242,"at_date":"2022-11-01 00:00","total_energy_consumption_at_date_kwh":0,"current_status":"","timestamp":"2022-11-21T19:59:31Z","device":"im871a[00103812]","rssi_dbm":-47}`

What do I need to change to T1? Is it possible?

Thanks for the hard work!!

**Comment by Xaver445** [comment]
Ein Anfänger schreibt:
Hallo, habe auch einen WMZ-Wärmemengenzähler von Kamstrup Multical 303 an meinen Pelletofen . Neu, habe ich als Driver kamheat eingeben(Ver. 1.10.1 05.12.2022  23:45h).  Erhalte hierzu Daten, heißt ich erhalte Daten. Kann dies nicht weiterverarbeiten. Gibt es hierzu einen link ?

hier eine Kopie:

wmbusmeters auto:c1 Mein-WMZ iperl:c1 827xxx01 1E93BF9D79xxxxxxxxxx211EF38FBD74A
Started auto cul on /dev/ttyUSB0 listening on c1
(meter) Mein-WMZ: meter detection did not match the selected driver iperl! correct driver is: kamheat
(meter) Not printing this warning again for id: 827xxx01 mfct: (KAM) Kamstrup Energi (0x2c2d) type: Heat meter (0x04) ver: 0x40
Mein-WMZ	827xxx01	324.74 m³	0.009 m³/h	2022-12-07 17:21.49
Mein-WMZ	827xxx01	324.74 m³	0.009 m³/h	2022-12-07 17:22.05

verstehe es nicht wie man es an MQTT durchreichen kann .?

Hoffe auf ein Feedback .
