### ISSUE TITLE
Sagecom EF4EVO Gas meter

### ISSUE THREAD

**Issue by sgargel** [wmbusmeters/wmbusmeters#702]
My gas and energy reseller company installed in my house this new " smart meter with remote communication and management system".

https://www.sagemcom.com/V02/fileadmin/user_upload/Energy/Electricity/Niv4/Meter_Italia/EF4EVO.pdf

As stated in the User Manual provided, it uses Wireless M-Bus 169 Mhz radio-communication and communication protocol DLMS-COSEM.

As I want to try to have a remote measurement read of my gas usage, I tryed to capture radio signals with `rtl_433 -f 169728051 -s 1600000 -S all -A` and after about 10 hours of nothing, I found some 'cu8' files saved on my disk.

[20221115.zip](https://github.com/weetmuts/wmbusmeters/files/10098517/20221115.zip)

I'm not sure how to "read" them and also I'm not sure if those signals can
 be in any way "decoded". 

Any help or comment will be very appreciated.

Thanks!

**Comment by BIBOLV** [comment]
Please check https://github.com/weetmuts/wmbusmeters/issues/677

**Comment by wilds** [comment]
I think this could be useful:
DLMS COSEM library https://github.com/Gurux/GuruxDLMS.c
