### ISSUE TITLE
Bad or no communication with APATOR 17-2 on Pi ?

### ISSUE THREAD

**Issue by titithebad** [wmbusmeters/wmbusmeters#704]
Hello,

I am running these tools on a Raspberry pi B+ with Bulleseye Rapsbian distribution.

My meter has the serial 1356258. So I think that my telegram is 0014B1E2.

As I run : **_sudo wmbusmeters --debug auto:t1 watermeter apator162 0014B1E2 NOKEY_**, I have got these : 
_____________
(wmbusmeters) version: 1.9.0-151-g9a8cd21
(config) number of meters: 1
(main) device /dev/ttyAMA0 not currently used, detect contents...
(serial) check if /dev/ttyAMA0 can be accessed
(serial) tty /dev/ttyAMA0 can be accessed
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyAMA0 speed(B115200) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serial) after config:  /dev/ttyAMA0 speed(B9600) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serialtty) opened /dev/ttyAMA0 fd 3 (detect amb8465/amb3665)
(serial) received binary ""
(amb8465/3665) sending 6 bytes attempt 0
(serial /dev/ttyAMA0) sent "FF0A02008077"
(serial) EVENT thread interrupted
(amb8465/3665) sent 6 bytes OK
(amb8465/3665) reading response... 1
(serial) received binary ""
(amb8465/3665) reading response... 2
(serial) received binary ""
(amb8465/3665) reading response... 3
(serial) received binary ""
(amb8465/3665) are you there? no.
(serial) EVENT thread interrupted
(serialtty) closed /dev/ttyAMA0 (detect amb8465/amb3665)
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyAMA0 speed(B9600) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serial) after config:  /dev/ttyAMA0 speed(B57600) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serialtty) opened /dev/ttyAMA0 fd 3 (detect im871a)
(serial) received binary ""
(serial /dev/ttyAMA0) sent "A5010F00"
(serial) EVENT thread interrupted
(serial) received binary ""
(im871a/im170a) are you there? no.
(serial) EVENT thread interrupted
(serialtty) closed /dev/ttyAMA0 (detect im871a)
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyAMA0 speed(B57600) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serial) after config:  /dev/ttyAMA0 speed(B19200) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serialtty) opened /dev/ttyAMA0 fd 3 (detect rc1180)
(serial /dev/ttyAMA0) sent "00"
(serial) EVENT thread interrupted
(serial) received binary ""
(serial /dev/ttyAMA0) sent "30"
(serial) EVENT thread interrupted
(serial) received binary ""
(serial) EVENT thread interrupted
(serialtty) closed /dev/ttyAMA0 (detect rc1180)
(rc1180) are you there? no.
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyAMA0 speed(B19200) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serial) after config:  /dev/ttyAMA0 speed(B38400) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serialtty) opened /dev/ttyAMA0 fd 3 (detect cul)
(serial /dev/ttyAMA0) sent "560D0A"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serial /dev/ttyAMA0) sent "560D0A"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serial /dev/ttyAMA0) sent "560D0A"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serial) EVENT thread interrupted
(serialtty) closed /dev/ttyAMA0 (detect cul)
(cul) are you there? no
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyAMA0 speed(B38400) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serial) after config:  /dev/ttyAMA0 speed(B115200) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS|CTS)
(serialtty) opened /dev/ttyAMA0 fd 3 (detect iu880b)
(serial) received binary ""
(serial /dev/ttyAMA0) sent "C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0"
(serial) EVENT thread interrupted
(serial /dev/ttyAMA0) sent "C001030424C0"
(serial) EVENT thread interrupted
(serial) received binary ""
(iu880b) are you there? no.
(serial) EVENT thread interrupted
(serialtty) closed /dev/ttyAMA0 (detect iu880b)
(main) ignoring /dev/ttyAMA0, it does not respond as any of the supported wmbus devices.
(shell) exec (capture output) "/bin/sh"
(shell) arg "-c"
(shell) arg "rtl_sdr < /dev/null"
(shell) output: >>>rtl_sdr, an I/Q recorder for RTL2832 based DVB-T receivers

Usage:	 -f frequency_to_tune_to [Hz]
	[-s samplerate (default: 2048000 Hz)]
	[-d device_index (default: 0)]
	[-g gain (default: 0 for auto)]
	[-p ppm_error (default: 0)]
	[-b output_block_size (default: 16 * 16384)]
	[-n number of samples to read (default: 0, infinite)]
	[-S force sync output (default: async)]
	filename (a '-' dumps samples to stdout)

<<<
(shell) return code 1
(serial) EVENT thread interrupted
(shell) 2285 exited
(main) rtl_srd found in path
(shell) exec (capture output) "/bin/sh"
(shell) arg "-c"
(shell) arg "rtl_wmbus < /dev/null"
(shell) output: >>><<<
(shell) return code 0
(shell) 2287 exited
(main) rtl_wmbus found in path
(main) rtlsdr device 00000001 not currently used.
(serial) EVENT thread interrupted
(main) opening rtlwmbus
Started auto rtlwmbus[00000001] listening on t1
(rtlwmbus) using command: /usr/bin/rtl_sdr  -d 0 -f 868.625M -s 1.6e6 - 2>/dev/null | rtl_wmbus -s
(rtlwmbus) opening 00000001
(serial) EVENT thread interrupted
(bgshell) exec background "/bin/sh"
(bgshell) arg "-c"
(bgshell) arg "/usr/bin/rtl_sdr  -d 0 -f 868.625M -s 1.6e6 - 2>/dev/null | rtl_wmbus -s"
(serialcmd) opened /bin/sh pid 2294 fd 5 (rtlwmbus)
(main) regular reset of rtlwmbus  will happen every 82800 seconds
(wmbus) no alarm (expected activity) for rtlwmbus
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
(serial) waiting for stop
___________________

Before the I run **_rtl_test -t_** : 
____________
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6 
[R82XX] PLL not locked!
Sampling at 2048000 S/s.
No E4000 tuner found, aborting.
____________

I think that something is wrong but I do not know what... Can you help me ?

Thanks

Regards

**Comment by BIBOLV** [comment]
Hi,
I would suggest to run following command for a while and search in all received telegrams on from your meter,
`sudo wmbusmeters --debug rtlwmbus:CMD(rtl_sdr -f 868.95M -s 1600000 - 2>/dev/null | rtl_wmbus -p s -a)`
