### ISSUE TITLE
Telegram unknown size apator162

### ISSUE THREAD

**Issue by listek2336** [wmbusmeters/wmbusmeters#705]
Hi, i have problem with my apator 162 i have this error

telegram=|3E4401067396040305077A9F0030852F2F_0F325D4B9630000040BCD7D3F1F3F341545842403CA400F00101000010B28B0100FFFFFFFFFFFFFFFFFFFFFF4E66|+81
(apator162) telegram contains a register (d3) with unknown size.
Please open an issue at https://github.com/weetmuts/wmbusmeters/
and report this telegram: 3E4401067396040305077A9F0030852F2F0F325D4B9630000040BCD7D3F1F3F341545842403CA400F00101000010B28B0100FFFFFFFFFFFFFFFFFFFFFF4E66

**Comment by weetmuts** [comment]
Fix pushed! Please test!
