### ISSUE TITLE
Question: Sharky 775 - frequency ?

### ISSUE THREAD

**Issue by bipsendk** [wmbusmeters/wmbusmeters#716]
My Sharky 775 is labeled with 868MHz, but is there a hint for a more exact frequency ?

Also, is there a way to find out if the heating supply company uses LoRa-WAN instead of WM-Bus ?

**Comment by weetmuts** [comment]
You can either find your ppm and supply it to the device setup, eg: "rtlwmbus(ppm=17)"
(google find your ppm rtlsdr)

Or change the frequency using either: "rtlwmbus:868.95M"
or a full command if you do not need s mode.
"rtlwmbus:CMD(rtl_sdr -f 868.95M -s 1600000 - 2>/dev/null | rtl_wmbus -p s)"

Change 868.95M between 868.90M up to 869.00M or so....
