### ISSUE TITLE
AXIOMA / QUALCOSONIC W1 decoding

### ISSUE THREAD

**Issue by MartinSlachta** [wmbusmeters/wmbusmeters#727]
I read data from AXIOMA / QUALCOSONIC W1 and looks like two items are missing. Is it possible to fix it ? Thx, Martin

![image](https://user-images.githubusercontent.com/64375280/206273932-b4110974-3c2b-4b06-904c-87044070582b.png)

 wmbusmeters --analyze 544409076391820510077ABF100000046D2A0DC62C0420E80F430104130000000004933B0000000004933C00000000023B00000259F0D8446D0000C12C44130000000044933B0000000044933C0000000001FD7461
Auto driver  : q400
Best driver  : q400 36/41
Using driver : q400 00/00
000   : 54 length (84 bytes)(TEMPORARY_ERROR)
001   : 44 dll-c (from meter SND_NR)
002   : 0907 dll-mfct (AXI)
004   : 63918205 dll-id (05829163)
008   : 10 dll-version
009   : 07 dll-type (Water meter)
010   : 7a tpl-ci-field (EN 13757-3 Application Layer (short tplh))
011   : bf tpl-acc-field
012   : 10 tpl-sts-field (TEMPORARY_ERROR)
013   : 0000 tpl-cfg 0000 ( )
015   : 04 dif (32 Bit Integer/Binary Instantaneous value)
016   : 6D vif (Date and time type)
017 C!: 2A0DC62C ("meter_datetime":"2022-12-06 13:42")
021   : 04 dif (32 Bit Integer/Binary Instantaneous value)
022   : 20 vif (On time seconds)
MISSING
023 C?: E80F4301
027   : 04 dif (32 Bit Integer/Binary Instantaneous value)
028   : 13 vif (Volume l)
029 C!: 00000000 ("total_m3":0)
033   : 04 dif (32 Bit Integer/Binary Instantaneous value)
034   : 93 vif (Volume l)
035   : 3B combinable vif (ForwardFlow)
036 C!: 00000000 ("total_forward_m3":0)
040   : 04 dif (32 Bit Integer/Binary Instantaneous value)
041   : 93 vif (Volume l)
042   : 3C combinable vif (BackwardFlow)
043 C!: 00000000 ("total_backward_m3":0)
047   : 02 dif (16 Bit Integer/Binary Instantaneous value)
048   : 3B vif (Volume flow l/h)
049 C!: 0000 ("volume_flow_m3h":0)
051   : 02 dif (16 Bit Integer/Binary Instantaneous value)
052   : 59 vif (Flow temperature 10⁻² °C)
053 C!: F0D8 ("flow_temperature_c":555.36)
055   : 44 dif (32 Bit Integer/Binary Instantaneous value storagenr=1)
056   : 6D vif (Date and time type)
057 C!: 0000C12C ("set_datetime":"2022-12-01 00:00")
061   : 44 dif (32 Bit Integer/Binary Instantaneous value storagenr=1)
062   : 13 vif (Volume l)
063 C!: 00000000 ("consumption_at_set_date_m3":0)
067   : 44 dif (32 Bit Integer/Binary Instantaneous value storagenr=1)
068   : 93 vif (Volume l)
069   : 3B combinable vif (ForwardFlow)
070 C!: 00000000 ("forward_at_set_date_m3":0)
074   : 44 dif (32 Bit Integer/Binary Instantaneous value storagenr=1)
075   : 93 vif (Volume l)
076   : 3C combinable vif (BackwardFlow)
077 C!: 00000000 ("backward_at_set_date_m3":0)
081   : 01 dif (8 Bit Integer/Binary Instantaneous value)
082   : FD vif (Second extension FD of VIF-codes)
083   : 74 vife (Reserved)
MISSING (looks like battery 97 %)
084 C?: 61

**Comment by weetmuts** [comment]
@MartinSlachta Thanks for the telegram and the explanation for the battery percentage field! 
They are added now!
