### ISSUE TITLE
resetafter - not working

### ISSUE THREAD

**Issue by testuser7** [wmbusmeters/wmbusmeters#737]
I have a problem with the rtl usb dongle (Astrometa DVB-T2). It stops working after some time.
The resetafter option does not work:
```
/wmbusmeters # ./wmbusmeters --resetafter=10s --donotprobe=all --debug "rtlwmbus:CMD(rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | rtl_wmbus -p s -a)" MyWater izar '*' NOKEY
(wmbusmeters) version: 1.10.1
(config) using device: rtlwmbus:CMD(rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | rtl_wmbus -p s -a) 
(config) number of meters: 1
(serial) expecting devices to work
(serial) expecting devices to work
(lookup) with cmd "rtlwmbus:CMD(rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | rtl_wmbus -p s -a)"
(main) opening rtlwmbus:CMD(rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | rtl_wmbus -p s -a)
Started config rtlwmbus listening on none using CMD(rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | rtl_wmbus -p s -a)
(rtlwmbus) using command: rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | rtl_wmbus -p s -a
(rtlwmbus) opening cmd_0
(bgshell) exec background "/bin/sh"
(bgshell) arg "-c"
(bgshell) arg "rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | rtl_wmbus -p s -a"
(serial) EVENT thread interrupted
(serialcmd) opened /bin/sh pid 868 fd 3 (rtlwmbus)
(main) regular reset of rtlwmbus  using CMD(rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | rtl_wmbus -p s -a) will happen every 10 seconds
(wmbus) no alarm (expected activity) for rtlwmbus
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
(serial) waiting for stop
```
Output from rtl_sdr:
```
/wmbusmeters # rtl_sdr -f 868.95M -s 1.6e6 -
Found 1 device(s):
  0:  astrometadvbt2, dvbt2, SN: 

Using device 0: Astrometa DVB-T/DVB-T2
Found Rafael Micro R828D tuner
[R82XX] PLL not locked!
Sampling at 1600000 S/s.
Tuned to 868950000 Hz.
Tuner gain set to automatic.
Reading samples in async mode...
Allocating 15 zero-copy buffers
```
and rtl_433:
```
/wmbusmeters # rtl_433 -f 868.95M -s 1.6e6
rtl_433 version 22.11-18-g686d9967 branch master at 202212051259 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/root/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...

New defaults active, use "-Y classic -s 250k" for the old defaults!

Protocols: Registered 191 out of 223 device decoding protocols [ 1-4 8 11-12 15-17 19-23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 170-175 177-197 199 201-215 217-223 ]
SDR: Found 1 device(s)
SDR: trying device  0:  astrometadvbt2, dvbt2, SN: 
Found Rafael Micro R828D tuner
SDR: Using device 0: Astrometa DVB-T/DVB-T2
[R82XX] PLL not locked!
SDR: Sample rate set to 1600000 S/s.
SDR: Tuner gain set to Auto.
SDR: Tuned to 868.950MHz.
Allocating 15 zero-copy buffers
Async read stalled, exiting!
```
The device is recognized correctly:
```/wmbusmeters # rtl_eeprom
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2

Using device 0: Astrometa DVB-T/DVB-T2
Found Rafael Micro R828D tuner

Current configuration:
__________________________________________
Vendor ID:		0x15f4
Product ID:		0x0131
Manufacturer:		astrometadvbt2
Product:		dvbt2
Serial number:		0011
Serial number enabled:	no
IR endpoint enabled:	yes
Remote wakeup enabled:	no
__________________________________________
```

**Comment by testuser7** [comment]
Usbreset is able to properly reset dongle.
Is it possible to add usbreset to a docker image?
```
docker run -v /dev/bus/usb:/dev/bus/usb --privileged rugarci/usbreset:dev /dev/bus/usb/001/004            
go with /dev/bus/usb/001/004
Resetting /dev/bus/usb/001/004
Resetting USB device /dev/bus/usb/001/004
Reset successful
```

**Comment by testuser7** [comment]
After switching from rtl_sdr to rtl_433 the dongle works stably (or is properly reset).
Is reset being logged?

Is there any way to skip logging `(rtl433) dll_len adjusted to 27 from 23. Fix rtl_433? This warning will not be printed again.`?
I'm reading the izar meters with command: `rtl_433 -R 104 -Y squelch -F csv -f 868.95M`.

**Comment by testuser7** [comment]
Today my dongle hang again.
rtl_433 is exiting with `Async read stalled, exiting!`

wmbusmeters logs (verbose):

**Comment by weetmuts** [comment]
Ah, there is a segfault.... can you figure out where the segfault happens using gdb and your wmbusmeters binary?
gdb --args wmbusmeters 
Then info symbol 00007fee4d32db44
to find the function?

If you built wmbusmeters yourself there might be a wmbusmeters.g in the build directory
with more debug symbols.

Or build a DEBUG=true version of wmbusmeters and reproduce the error with that? Then it should
print the segfault location on stderr.

**Comment by weetmuts** [comment]
There is a second ip 0x00007fc5333d5b4c
Perhaps rtl433 crashed and took wmbusmeters with it.

**Comment by testuser7** [comment]
Yes, rtl_433 exits with an error and wmbusmeters crashes. I'm using docker image.

I think that dongle reset should be implemented in rtl_sdr and rtl_433.
Currently, only rtl_433 detects a dongle hang with the error: `Async read stalled, exiting!`. rtl_sdr waits for data indefinitely.
usbreset solves the problem as always.

Here some attempt to implement a reset tool (based on rtl_test): https://github.com/ED6E0F17/rtl_reset

**Comment by weetmuts** [comment]
The option --resetafter kills the subprocess, ie the subshell running rtl433 or rtlsd+rtlwbus. Then starts it again. Nothing more.

Can you reproduce the problem without docker?

**Comment by testuser7** [comment]
Thanks for the clarification.
I'm running docker on Qnap NAS (x86_64).
I can try to build binary for this system.

**Comment by testuser7** [comment]
Here is a example how to solve this problem using python: https://raspberrypiandstuff.wordpress.com/2017/08/04/rtl_433-on-a-raspberry-pi-made-bulletproof/
