### ISSUE TITLE
Missing driver for warm water hydrometer

### ISSUE THREAD

**Issue by geraldloss** [wmbusmeters/wmbusmeters#795]
Hi hi,

got a new hydrometer with unknown driver.

Received telegram from: 1485XXXX
          manufacturer: (TCH) Techem Service (0x5068)
                  type: Radio converter (meter side) (0x37)
                   ver: 0x95
      Concerning meter: 7417XXXX
          manufacturer: (HYD) Hydrometer (0x2324)
                  type: Warm Water (30°C-90°C) meter (0x06)
                   ver: 0xfe
                device: rtlwmbus[00000001]
                  rssi: 125 dBm
                driver: unknown!

Here some telegrams I catched:
telegram=|1744685094148514953772746717742423FE06EB000000|2F|+15
telegram=|1744685094148514953772746717742423FE06EB000000|2F|+64
telegram=|1744685094148514953772746717742423FE06EC000000|2F|+113
telegram=|1744685094148514953772746717742423FE06EC000000|2F|+162
telegram=|1744685094148514953772746717742423FE06EC000000|2F|+211
telegram=|1744685094148514953772746717742423FE06ED000000|2F|+359
telegram=|1744685094148514953772746717742423FE06ED000000|2F|+408
telegram=|1744685094148514953772746717742423FE06ED000000|2F|+457
telegram=|1744685094148514953772746717742423FE06ED000000|2F|+506

Would be great if you could provide a driver for this device. Tell me if you need additional informations.

Thank you and best regards
Gerald

**Comment by BIBOLV** [comment]
Hi,
Could you collect more telegrams that are not like you already provided because all of them are the same and there are no details in them except info about meter side converter details. You can check [here](https://wmbusmeters.org/analyze/1744685094148514953772746717742423FE06ED0000002F) .
