### ISSUE TITLE
Watertech WTT 

### ISSUE THREAD

**Issue by Fiorello8** [wmbusmeters/wmbusmeters#811]
Hello !

Thanks for your fantastic software!

Unfortunately I have a problem with the detection of  the frames from one type of smart meter

when I try to decode I receive the following error 

(meter) contatore: meter detection could not find driver for id: 02105681 mfct: (WTT) Watertech, Italy (0x5e94) type: Water meter (0x07) ver: 0x59
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
(wmbus) WARNING!! decrypted content failed check, did you use the correct decryption key? Permanently ignoring telegrams from id: 02105681 mfct: (WTT) Watertech, Italy (0x5e94) type: Water meter (0x07) ver: 0x59
(meter) newly created meter (contatore 02105681 auto) did not handle telegram!

If I use the website https://wmbusmeters.org/ (see the photo)  I can receive all the information except one (no important for me)
I would like to read this frame also via script.. Is it possible ?

Can you help me ?

![Immagine](https://user-images.githubusercontent.com/115693320/213156618-ccd13ea6-e7a1-44ca-9543-47d2b19eb481.png)

**Comment by BIBOLV** [comment]
Hi,
Can you post few telegrams here?
Also, yuo will need to elaborate what you mean by reading frame with as script.

**Comment by Fiorello8** [comment]
Hi

for the telegrams see below
the password is always e7ac09ce9e902d3aaf23eb592aa01973

I would like to use wmbusmeters via command line but with this type of
smart meter I have not a good result...

I am using

*wmbusmeters: 1.9.0-43-g0125e520125e52da723b804375e8b5075763e272897489c*

If I use the web application
*https://wmbusmeters.org/analyze/3144945e3839100259078c20007a01002025a354a553e521bd56c37ceeac2297a8aa99adcf9f064310008ec7224459641b26:auto:e7ac09ce9e902d3aaf23eb592aa01973
<https://wmbusmeters.org/analyze/3144945e3839100259078c20007a01002025a354a553e521bd56c37ceeac2297a8aa99adcf9f064310008ec7224459641b26:auto:e7ac09ce9e902d3aaf23eb592aa01973>*
I have the correct result (i am not interested in a last value in red)

3144945e6456120259078c20687a69002025116f495887e0df8b153a9dc079344f63677baf8f1f501bda3943e92ce7ba7a6c
3144945e0958120259078c20997a9a00202548aa599b90a35d4783bdf20a4a0d87f67a6e44dfd592bd611c6b27433f9bbc6a
3144945e4846100259078c20477a48002025000a4beb17804e55cf71f159bdf45c92b2e0c9126e6337a7ef0508b91e8e834e
3144945e4646100259078c206f7a70002025bef3d1f32deff738b350d07ac5bcbac5e5ab80cf87bcea5c17f09d8408dd934b
3144945e6244100259078c20dd7ade002025c81c92f79d84cb4f313bb85ea202150ff582d878545f45e5e2e060cda7823fae
3144945e1457120259078c20497a4a002025937663f9c3b3406d646f201be05828b3a4b06d30c1f5d26bd4e7bd95cb0d1bf1
3144945e7226120259078c20bc7abd002025b3aff2ab40a04a811c137526bdc26422bc56505ca746d95d325764e7de27d544
3144945e1128100259078c20ea7aeb00202515902389bf64dd9a82761cf6e0766be13ed53955e43d09b0b83c4cc4beeac1d6
3144945e5959100259078c20f47af5002025f78a262be0e94ed6d8135652fda4aed11e206c58363065eb5793b57a8b5e734d
3144945e2755120259078c206d7a6e002025a26d3bf7f947ddb16f131953730c3bdaec887cb8ec16399b5181f28266bd5cbc
3144945e5259100259078c20197a1a002025945973d743b5ac926cc7a5f179271e649b9b14f440c751defac303cf59d7bbbe
3144945e0456120259078c20267a27002025933a9dca0c21ee62f1ae34c33e981d68da67b876d18a3f087595358481acafab
3144945e2656100259078c20fc7afd002025d76e1b2b0746cdc7dbb5babde5b6a19a67a8f76e4dd58d10295163018ae73098
3144945e2728100259078c204a7a4b00202501438d4bd94487f393eee349e936f1fa8b2f88e807ad324336d0a5a18eb9170a
3144945e4058120259078c20277a28002025c6371303deff381b2f7dc6ae2b8eca72c80eebccff8accf0686620e86d331bec
3144945e3949100259078c20097a0a0020255e943f60bcaa84fcbe7444948b7caf7bafaf916770c126ccdfe9f13f9e70c620
3144945e6244120259078c201e7a1f0020257d6d2ec67ac415d8e25a173e2e934228a5362791a708f495cb00a5454c68a438
3144945e6045120259078c20c47ac50020259a4b0db9041558c755b3a32a010db448aa5b860cac7eedc75ea1ed78d81cf1ef
3144945e8148100259078c201a7a1b002025774e165dab59e86459b026a8fefd7bd1b642672c1899ef2c35574cccdf2d8a6d
3144945e6045100259078c20687a6900202554523444854c4a8f191463dd5c14d2708ec6c03ead3be9c52d71d4d1db5c80ff
3144945e3156120259078c20d27ad30020257765d2524eb74a02a6c71b049f24a211f5b99fb410ebdee9d7dd1fbec81ccc0b
3144945e1344100259078c20ba7abb002025c7027634afd2e7d340c0f43668af4eba04411a1797dbf835324f9236868a845c
3144945e0844100259078c20967a97002025c87300138568b7a2edaa3611f2b4e1213bf187b4d11eb5f3ea686882c7c00549
3144945e1856100259078c20817a82002025c5f788130dd0d272e996a61534cda41acbd7094c2d4a51677563efeeca4e9775
3144945e5045100259078c20287a290020253778b32c9b7be53a505fc9ed979ee4c23139e9ca8703549255d502cd64ba6f9c
3144945e2544120259078c20807a810020257fb23faac75597fd0594b10e09dfa665439488ce1fcc3a4e521d7ada69926d37
3144945e5526120259078c20487a49002025cd25faac1f398bfb87212072f648d418a2a69d7eebdca57b0440e069ba75bcda
3144945e8227100259078c206d7a6e00202575aeedd6615acb05038f03317ccf8cbc4b5fa4c85860fa3d94f26e75148579b8
3144945e0442120259078c20e97aea002025a27ca6b85b0573f5ef2c5ba5d27d804638d5d6b86a526e737747d25e7b78d74d
3144945e4256100259078c20607a610020254993a767d5eeac01aae35d05942754d0043a888692ef7eb85035044c766a7851
3144945e1145120259078c20ed7aee002025b9cc9bcf0d99e446c0bdd42e0f83e1b80c56d144ae752e38747fbe9e7cf63802
3144945e5858120259078c20e57ae60020257ab8ca47086de4fcbf5607ea6cb795c857ccab637bbf26b82cb2c30e0afe2906
3144945e9842120259078c20167a170020259862aba7116116d945d4a3e3fbfb295f7248d4c08cea309260ee79b13742645b
3144945e0657100259078c20f37af4002025f67a677ff6445051082e8468d08278d48f84c2b309a8522ef13a22c13d1c1878
3144945e1043120259078c20427a430020257d116f00102824ed3b07af84c54b7e74bfbc3546e88205c681393647faea0cc8
3144945e3944120259078c20b27ab300202573d7370a22a170399a431137d02067079e527a3a0d1ea0c7dc3b9da666228d76
3144945e0043120259078c20857a860020250aa24d208c079fa4d64a7787db3146cf8acb00797c11351654a2b6fba8a88b25
3144945e6146100259078c20027a030020252a837f2e3e85d541bb3581bcfc105eccfac9c82c3b7d7f5e5b63f5a7c673b156
3144945e1258120259078c20d77ad8002025e9185ca13bc3f08310c96521406a466ad70c639b15c3658ae500fc571f84d611
3144945e0956100259078c20877a880020257f7375880b775d3698ef1696425f2fc401fa8142b0d84aa17a0f79c6418842e1
3144945e9026120259078c20207a2100202545ab24e5440824062e152f4b2c3ad759849a287fd1fed41bae24aa8d96378b71
3144945e9158100259078c20d07ad10020254ea1c413f928d8f4a5c4313c2d7a2d8cc3016bcac3055b7fee5872bc050a7058
3144945e1644120259078c20487a490020251af9392045728d75fb0bb84078a40e4c8a28fdcb60b7a7ef0f8c6d6a8f178430
3144945e9745100259078c20c17ac2002025c8902192bb2a83f60b3aab6d09d08e494973fec6f101ad9dcbfe5cdcf90ae2a8
3144945e2444100259078c200c7a0d002025ab7ecc8d88efc60d7e6824f12c50e4a5b78e407553e4ee4aab7adef8cc4f629d
3144945e6555120259078c20127a1300202507952b4a9d37149925dd49abeda0fa9539614afd09041e43b24e224d10262e2c
3144945e3558120259078c20527a5300202529a30416338cf5c4881b56e13837a529a2acfddbf5db601d768c45c8b4427f1c
3144945e8457100259078c20b17ab2002025d55c6e94d06433acd17c22d5fa67fa69ca9f1609e216ba4e9b907970e20c850a
3144945e0156120259078c201b7a1c002025eb0654e57670f2b4a08bb7214b8a0c8e7b8daf664b2c1a0c90ab8c7ef2d5bb57
3144945e5443120259078c20627a63002025aa98d40a211caa43320f328f95fcdf75bf7e0ad1ef5d1945df9383e53f7490ad
3144945e1943120259078c20837a8400202504b4c78d8a5b3f707ba3c8fde0b26aea60aeca0d7c04b037594a5f867f28f563
3144945e9845100259078c206e7a6f002025a3e500db978cb0606f956f9d32a21082e230f236b66cc626407ca8b280e9c283
3144945e9327100259078c20c37ac40020251771d2e4a1da7d64954a4214ab7f6b0c21b9a2dd76612358b78d0afd22d02de6
3144945e6058120259078c20607a61002025c2300a979c7fddb7a1d0a78be9cc3b0a2f93ff44485372a796e84e1e8a3b3745
3144945e2943120259078c20937a94002025165b03eb27cd882afedf787e5b3d36b0273b4b7a216158aadee21182f528074c
3144945e2644100259078c20507a51002025c8615463ca4ebeef5c78e4941dcdad816697d151aa3d89d67b5871d7671be985
3144945e2843120259078c207c7a7d0020252cc3e99016ff578db74904c9f7d0398b42ae9638ca88657a4358277f4c5770fe
3144945e4256120259078c20557a560020259fc6efc1674c9f260ab3a16be73a37ad5447676cb193aad739689f06c95fe46d
3144945e1844120259078c20047a050020250e7f5641c65dd628919d4ab415198b76d34d2fe08df14319d846f2caee9188b9
3144945e4756120259078c20d97ada00202508f8dbbf59f7948c933767684957995860c4457afb7a425ef299eeff2af4476c
3144945e0456100259078c20637a64002025e9bd9e13f8886ec75a740d313c8b5fe812d1121305708665865b7c9bcfaa68ca
3144945e8258100259078c20377a38002025181b5a0932537f1ecf5fae29d6e0f0e49a77f0de502626f188e24446f46070b6
3144945e0047100259078c20e27ae3002025b82b7ecabc669d2240a6fd35559f446ebfbbeed8505b1e93f18659ec01223e3c
3144945e6356100259078c20817a82002025d48b67cbac364f75bc04bbf8f2c319aa4f5410cb05af1a1ef9ce41ddf1cb125f
3144945e1058120259078c207e7a7f002025884875757d959fb6439db77b8718b881eaaa5843c74d7f46bf5f9756e587ee04
3144945e3458120259078c20b37ab4002025d6dcdee426a683ff25705dd9e1a3d6e0d41e257efbbf8414c1cf76700e0178c6
3144945e5459100259078c20ef7af0002025c286e99588c03e278c7dcb8ceb11af04442235b56c1dbc91a4feae075bc379fb
3144945e2546100259078c20437a44002025de0fd876506944f346626f46a2003eaf8dadefbdc1776e21257009d8542f34c9
3144945e1855120259078c20947a95002025cf2416039a6111afd2cfdbbd0839344e06fcc102dd976321360e92487f2d619b
3144945e9459100259078c20c67ac70020252f38b45f111fcd22fd421811c16e06299c164a8bfb109a5a64fce141c77d9d65
3144945e3845120259078c204a7a4b002025d4d946240ad3056aa1925b221b26480e210eb81bf045c4f57739ba8b9dc12ccd
3144945e4828100259078c20b57ab60020251720de8515a54dcd23c8cb8cad7f018405f083aa92e920e7590e3ae29ff63a78
3144945e0956120259078c201c7a1d002025bb61008f2e436c66978dc6ea55cb9ee98f4af0913e77d91a61ab6a246ce29243
3144945e5045120259078c20727a730020259523fd38ad713b925a014fc0c06e89ed7aef1d8e61b6446e120e53747feb02d8
3144945e5344100259078c20aa7aab002025f168f4baec1656f6172191f02a0253c2e45a72c7592fcbbece8fa7806900284b
3144945e3644100259078c20847a850020251c194d4c8e54826c4e15cdcf27575f57419a6df94fd1ab3a4f9a6d83e8d07fcb
3144945e0643120259078c20c67ac700202571d1521385ce06405f6f3134684b0ae955ace596fcea3c4e89e9ba33c4d9eb39
3144945e2528100259078c20e47ae5002025c7e04af74fb5226fc0c4e4ae737d5ed2f91d4ecc73474cf598a2716d56ac7939
3144945e0143120259078c20507a510020251efee5238dad1abce152cc60f69b781380cc57142983e869171737a02595ff66
3144945e9755100259078c20877a88002025c6fa88347aca745b1a48ddd7d6dd75c4e12ece34606dc1a90cde20a1c8e4891b
3144945e4543120259078c20b17ab2002025a6499ff7d91ca77f1385cd8fc01850e197f038cd280f1d8dd027b3fd60357352
3144945e0243120259078c20687a690020256d5dfd6b2c291c6366b33b17dd98cd0dcd67067ba59b4c13fc88b7d7467e1d81
3144945e5456100259078c20c57ac600202544a9542de72d8177d46422a7878918ad5172bb4f8a224f3f60127e631197cb35
3144945e6656100259078c20527a53002025cd85f07ebc1f3e4f9ad79feceb08ba79ab9e0f10a7fab0f60437bbeab0c7ddc0
3144945e1644100259078c209b7a9c002025c2abd4a93a32f9efa97d8f94472a7a25d4d7c077d3d2c770b1f86ec5efeb8c60
3144945e0655120259078c208b7a8c002025942820130d8fff0939597f3d14ca44a824c2d1cd0e4f33fdbbc38b57a52c95c5
3144945e5026120259078c208e7a8f002025edc08d92ebfa1c4dafe362b9f1a5298bcead59d9c1aa3ca9bed0fd426bf67c1c
3144945e6044100259078c20c67ac7002025468981782365e361956f230972cee46db2e4ed61f08b18c2174a4c08183383f3
3144945e8255120259078c201b7a1c00202530b89c0697fb6cc4d10f4d52a29e3e8e07792a6bd4b8ca76d26b0205f029e4ce
3144945e4643120259078c20227a23002025eeadc08ead5c59f625ad7e6685b7508b0727570d58d2c81e16784eef01c387e5
3144945e9942120259078c20057a0600202579b40fb0c4a50aca2ed6483a28388c4d226c7815394371258dfba613fbb0add8
3144945e6442100259078c204f7a50002025abd93cce1ee16eda534c1513ed750f091812bf50f3700c0b88a53f89a88eb359
3144945e6344100259078c20d57ad60020251d7693cee5af21f02d212fdaccb666d282d604202448c206bf30cb135e646901
3144945e4743120259078c200a7a0b002025891502b7f26db26cac1ff10f0bbb3383f4bb75b7c2ac3adb11ee9c545dbfb59f
3144945e4455120259078c20c97aca0020257f3097d12ada49032bbe7aa59265d9b53353d4ff5c787303392d805dc6c086bd
3144945e2945100259078c20a47aa50020252f52acc88c6818a89db21db2394ee571726a9cd53183e128c8f0f10e284bb44b
3144945e1444100259078c20267a270020257dc017b0a0a8f3b039f2621b2f61d26d2b958b8bd41591a726aec90f6abbdcc6
3144945e0528100259078c20927a9300202558c78075f7e4caeb51c721acb8a2b91756af587439d6beb96a12f97d1ac82002
3144945e0944100259078c20257a26002025b00d198afd3f59a3cd29fd79ca4fc71f47208446e1a2b171540bc54da3a62c22
3144945e2244120259078c20af7ab00020252c9ed605014d89c99c1c8bb5a320ba6a9f29a2823b6bf8cd065638827fdc5e32
3144945e6644100259078c203a7a3b00202570f12bf7e3aab13f1ab2599ea7a059279e053aad02f6f4e651971a555d5474ee
3144945e1257100259078c20b17ab2002025457de06d009ce6fbf604bbbf2324dac8857ace469a2e1fa0b7a50a9dee3223c5
3144945e4056100259078c20df7ae0002025038c9d6d9fa3a8e8ce0db7919ad210fe8c983144ab361e354220990b2bce3dda
3144945e8655120259078c204a7a4b0020252d53670ad0ab1956b329a6d2498f60280e01ad2fe6c2e4e37148e691c3441567
3144945e2343120259078c204c7a4d0020259d991e569db6789457ec72966fb3137d563fe8454b8eb1dec065f4b7394de6bd
3144945e4245100259078c20bf7ac00020253560470d08091af963aca059706532c224d0e925e771e5946045089b9d302c57
3144945e5841120259078c20e97aea002025010d8476a24047539b425022495be7e061b9bc3472599afb9c2357d87b5c378e
3144945e2745100259078c20ed7aee0020258cd6bff7ce66abdedbb682062db4e29d932b805b9a2eb2db87c01d482e8d2644
3144945e2045100259078c20417a420020258089ff33e44c329c7359d19ac221987775289eb445b17439f2363280c0e2e0e3
3144945e3457100259078c20887a89002025956fcd7869e0d709d52ef3b9cf49417717e1756df43df1d99209e227d435036c
3144945e1958100259078c20257a2600202540b6adaa87135185bfd7e9e7a8af422a0846af4ccc3a6ccc9ec070c786e451ab
3144945e0743120259078c20777a780020254a9344522b8a48ba63504cd10100376870ea8e124d46429fe62a264726d8b5f2
3144945e1442120259078c20397a3a002025106575b2f63ef60ddcdef253fa1f401052cbd76bf3cd29d6395594667b96eab8
3144945e6255120259078c202f7a30002025a362002bfc20d46c4ea71f6dd0e28a6fc5d4ac2882d31eae9622ddff735f0f66
3144945e1244120259078c20a47aa5002025162e525166617dcc56a121435864a71efaa79ca77a86ec98b6a88921f1affd65
3144945e2544100259078c20b77ab80020257506fed54317a67dc85b886e8a0b88f4673f0affdef8fc23559062c92c06b643
3144945e3043120259078c20cd7ace0020254f51189025777c414fb9b10d67abb3979edb2eaa18e2d22bc684f856458826d7
3144945e1143120259078c20d67ad7002025aa33ed11192307904d19eda08fb4ba464afa3bd630a00376bd125708ea2d0a67
3144945e6655120259078c20787a79002025a1975f810a2f3ed76df3abcab515eb0a389c8a6ae7257dca77b233226bbb3c16
3144945e2457120259078c20207a210020257c763fd80d0750a31af46e4a5805423bb222dbde50db6f4de9a6f0407046cbdd
3144945e9656100259078c209c7a9d002025687924bf8e12e778093f4b7e1af16e3036e771f01df08bd8d21524ef4067e338
3144945e6744100259078c20c97aca00202576011caba70cdb0e691497d26258918bc353995dd5c1b1bb4181e6167ce95823
3144945e5328100259078c20e17ae20020253a0bd2887f1583e9c202f29086ec0afc467c9ebd206297c55924011f5efcd061
3144945e6144100259078c20f27af30020256a71a1f1f5cb478652d2a41ebdebf0b550354b59ca2549e93e884fbef7c1695c
3144945e5143120259078c202b7a2c002025efa94fb1117e895681eb9ad44f6e40ef6fee3c76f393d7c72168bf871601946d
3144945e7156100259078c20bc7abd002025a87513728b921ec4d4ccf17e27e6fb51893adfd551da91188c3be326739f20f6
3144945e6355120259078c200f7a100020259aba7cae1d00188a447a76b597df24912976f027714a0d8a6d129fd03ce58218
3144945e5044100259078c20f17af2002025358b8b7c8b904f4a45f9113ba82dd8cfe95fa33bd379a337b3d4d61d8493ba4f
3144945e4243120259078c20ea7aeb002025a3cb8a40b67335a55307d10742fba19cb63c50bc4d7a6ea7bd9cfdb2ef539bb0
3144945e2237120259078c20677a680020254e7fbc4390fc082d75674b3267917e4d8bfcc916ba1ff222b4343222155faf1b
3144945e8841120259078c20937a9400202574b47f8bc7b6e6b2e6dc836bb692780ac867dce34600fc4d0cb5577e83e6463d
3144945e8857120259078c20857a8600202586b75ba70d0b183c51bb8b418290694916f0315072b2e4530535313ad4e0187f
3144945e9626120259078c20dc7add002025dba18b320fbf0caa81ecd28dc8d03ba115beb4447e4706ccd04e457a74c5ecee
3144945e2556100259078c20057a06002025fb77ac4a68e16b44c8a11bd9d2d1dccdcb8f6c73861d1d99f0a765522e26b448
3144945e3440100259078c20967a97002025567df19df95da11a6280fb1080918080dc7a73c9de729320391fa84fe61265fe
3144945e1243120259078c20c57ac60020251cebc0da15a4cd08b108c0c5d6381918bdaf40af4a1945bf395e6dd1aefe2bbf
3144945e8738120259078c20f57af6002025b2281838fe824715b6050ba84c68e6af1077862df6858847dbd8c00de38ff99a
3144945e2455120259078c20357a36002025e5f1183b0c04632ff4cd911d4d9e5861027e0c24dc6622853721a4d947a7d70d
3144945e2944120259078c20887a89002025196adbf9195ebd3dfca858f551d8afeb2b184d87a72413b04f2903f9e97518c2
3144945e3543120259078c20947a950020257ef771cf5861d727fdc421b54154899bb1d0a9e62c2798f49540fab3b4eb95fa
3144945e5144100259078c20c97aca00202595b8694ad31898e4054e2a2817a4c86069c1d38f592df600b832e5a85677fb36
3144945e3057120259078c20227a23002025a4650517373763056ae6dde4f6cf680a694f3f633113883ec546036ea3d9ab7c
3144945e6143120259078c20bf7ac0002025bbdde2e3400aa8a8e414f83446b35e97d296ffe8ff506faa2de6ca3d237f707c
3144945e7455120259078c20cd7ace002025374017726cb02c2fa1f97b388ec945e104b2c02aa40ddf7d8a2d9cfc92c9a0b4
3144945e7344100259078c205e7a5f0020256a1e40e9e1a60cf5474238dd43fa14f41b1ef23d693a1d204a797159cced2f6d
3144945e4544100259078c20027a0300202589b43426420be8d59ab3dac9d1f148a6f06ade17c5c678bad3e7c4195219092a
3144945e5743120259078c202c7a2d00202529c9ac9d8cfc5f48b45bc87f03faec2d75e77ae6e1457e3d8bccc476e99365da
3144945e3257120259078c20d37ad4002025f3317e706e63c324edcb63838ea64b9ca8b252ded1cff39e24429e29d2aed3f4
3144945e8855120259078c20c67ac7002025d5e74f3af5ed3a83a22e1de5053e9ce8ebbb0374be2e0a82455c463b746383da
3144945e3244100259078c205f7a60002025ba43d238b26d0dd58d2be28a0d6bc7d4d76e967c0b8f7536a37b6888251438d0
3144945e3458100259078c20ad7aae002025618e1ddb5afe8e2bec8a3e8ad0e2b863ecdc3834a238e79794bb81a671261e7b
3144945e5043120259078c20a17aa200202529cc8c7e8df8a24d8ef665029b2aeb445025fb176aab42f97218e6a629a6e327
3144945e4457120259078c20977a9800202505c1e95ad4bddde292264ff5de6f48061b78a6cb250f507b0f1e7630267e4917
3144945e7326120259078c20897a8a00202571d9042aa5edf647e3ef33dd58c15132092abf9693a3695e3736c294b100c472
3144945e3557120259078c20027a030020259cf9599bee1d6bf9ecafc26cf4b1895cae78f1b31e506c06ef91f7da4094a7f7
3144945e8627100259078c20a47aa500202529d05157baee1382276352b868ebf6ac3cdf5e5cafa7ff79a79983aa443d0bde
3144945e5958120259078c20037a040020252eb1f8ee942ac2c2d53c507740dfbee6dce1c50646695486e39e431efc0095b1
3144945e8546100259078c207a7a7b002025a93f6c90c5319fa54225cede0881409f524ecc288d1598e53025639af3d97c44
3144945e1844100259078c208f7a9000202535acf49bd44a625581df7b4843742b354630e7a3632b009123147ce97655b68f
3144945e4145120259078c20d67ad700202510b76f44f95cb3a80f5caf9bd21bd1fdbc0162dfe89fe2f2bfb0e5cc880428ce
3144945e0248120259078c20177a18002025aa9986630392f81272e64d5b98fa291d28d5b2995a168f40cecddc7d31910089
3144945e1060100259078c20537a54002025886cebf3f6dcb71922c34f3c3c08ff36b4ee06e3546b2c21081167087e7ab61c
3144945e7858120259078c20b27ab300202557dc9f540741e370cca2164c2f055ef0475bbc2fec14a10b096c1d6be96e6c94
3144945e3839100259078c20007a01002025a354a553e521bd56c37ceeac2297a8aa99adcf9f064310008ec7224459641b26
3144945e2159100259078c20257a26002025315b606ff4c7fae758c3eb84d3763349b52d39f623d69533d32e1879af8a0d3f
3144945e8156100259078c20c77ac800202557b9ba435c97e3985497dab5365e2cf173bb5f8afd79c17733388932194b602b


Il giorno mer 18 gen 2023 alle ore 15:20 BIBO ***@***.***> ha
scritto:

**Comment by BIBOLV** [comment]
Ok, please update to latest version and try then to see if everything works for you as expected.

**Comment by weetmuts** [comment]
I just added a watertech driver. It seems like watertech is a different company from those that produce waterstarm meters therefore the mft specific status bits are probably different, so we need a different driver.

Please test!

**Comment by Fiorello8** [comment]
The web application works fine !!!
How can I update the application in order to use the tool via command line ?





Il giorno mer 18 gen 2023 alle ore 16:47 Fredrik Öhrström <
***@***.***> ha scritto:

**Comment by weetmuts** [comment]
How did you install wmbusmeters in the first place?

**Comment by Fiorello8** [comment]
I have to update the installation of wmbusmeters on our linux (Debian)
machine ?

I tried to:

- download the code from github (wmbusmeters-master)
- copy the folder with the code on my Debain Virtual Machine
- follow the instruction noted at:
https://snapcraft.io/install/wmbusmeters/debian
- execute the command line "sudo make install" ... but I obtain the
following error

Building _
./scripts/generate_authors.sh build/authors.h
make: ./scripts/generate_authors.sh: Permission denied
make: *** [Makefile:241: build/authors.h] Error 127


if I execute wmbusmeters --version

I have as result

wmbusmeters: 1.9.0-43-g0125e52
0125e52da723b804375e8b5075763e272897489c

What I have to do to update the software ?


thanks in advance

Francesco





Il giorno mer 18 gen 2023 alle ore 18:25 Fredrik Öhrström <
***@***.***> ha scritto:

**Comment by BIBOLV** [comment]
I do not recommend to use snap version for scripts, better to use standalone installation. But if you would explain what you want to achieve, we could try to help with advice how to achieve it also withing snap version.

**Comment by Fiorello8** [comment]
Hi

I would like to use the command line with the new driver

wmbusmeters --format=json
1e44945e5243120259078c20a57aa6002025deb6f89c5049cd6da2b6f94e67932c917d50988ca6552abc748666fc4a6cae43
contatore1 waterstarm 02105722 E7AC09CE9E902D3AAF23EB592AA01900

but i am not able to upload the version.. this is my problem

I am using Debian... standalone version would be perfect for my purpose ...
Can you tell me how to download ?

Thanks



Il giorno mer 18 gen 2023 alle ore 22:28 BIBO ***@***.***> ha
scritto:

**Comment by BIBOLV** [comment]
All the documentation is available [here](https://github.com/weetmuts/wmbusmeters/blob/master/README.md). You would need to install all necessary tools, clone repo and compile/install.
