### ISSUE TITLE
shell= not working 

### ISSUE THREAD

**Issue by spagu** [wmbusmeters/wmbusmeters#821]
Hi,
I am trying to forward data to mqtt via wmbusmeters, having this config;

/usr/local/bin/wmbus-mqtt      
```bash
#!/bin/sh
/usr/bin/mosquitto_pub -h localhost -t wmbusmeters/woda -m "{\"total_m3\":${METER_TOTAL_M3}}"
```

and wmbusmeters.conf
```ini
loglevel=debug
# Remember to change auto here to the device you are going to use in production.
device=auto:t1
logtelegrams=true
format=json
meterfiles=/var/lib/wmbusmeters/meter_readings
meterfilesaction=overwrite
#meterfilesaction=append
logfile=/var/log/wmbusmeters/wmbusmeters.log
#shell=/usr/local/bin/wmbus-mqtt
shell=/usr/bin/mosquitto_pub -h localhost -t wmbusmeters/wasser -m "{\"total_m3\":${METER_TOTAL_M3}}"
```

When I execute the command manually by adding `ENV` it works on HA sees a value. But looks like wmbusmeters is somehow locked on executing a shell, what I am missing?

I did try:
- manual command
- debug shows it is executed with code 0
- data is read correctly 
- inside script added echo to /tmp/works - but it looks like it did not get executed.
-

**Comment by BIBOLV** [comment]
Hi,
What do you see in mqtt with `shell=/usr/bin/mosquitto_pub -h localhost -t wmbusmeters/wasser -m "$METER_JSON"` or `shell=/usr/bin/mosquitto_pub -h localhost -t wmbusmeters/wasser -m "$METER_TOTAL_M3"`
