### ISSUE TITLE
Sensostar driver: StorageNr for "consumption_%d_months_ago"

### ISSUE THREAD

**Issue by supaklass** [wmbusmeters/wmbusmeters#862]
### Type of request

Existing device improvement

### Meter description

Hi, 
I'm currently developping some logger software for my Engelmann Sensostar U heat meters. wmbusmeters ist a great startingpoint for that, but I discovered, that the historical meter data is not parsed correctly in the driver driver_sensostar.cc. The storageNr in the telegrams from the meter (in the DIF/DIFE) is always by 2 of the month, that means, that consumption_1_months_ago is at storageNr(2), consumption_2_months_ago at storageNr(4) and so on. 
The current implementation also causes a conflict with the field energy_consumption_at_reporting_date_kwh, whith is located at storageNr(1).
I fixed it with changing line 212 of the driver to .set(StorageNr(i*2))); This can be tested even with the telegram in line 225 in the driver. For further testing find a telegram below.
Regards, Robert.

### Logged telegrams from meter in decrypted format

```shell
BE44C5148093652400048C20BF900F002C25E51E0000AB9F24F74DB68ACA7ABF009007102F2F_046D152CEF220406970200000413FAC6000001FD1700426CDF2C440600000000840106990000008402060000000084030600000000840406000000008405060000000084060600000000840706000000008408060000000084090600000000840A0600000000840B0600000000840C0600000000840D0600000000840E0600000000840F06000000002F2F2F2F2F03FD0C05000002FD0B3141
```

**Comment by BIBOLV** [comment]
Hi,
Thanks for information!
Could you create PR for this fix?
