### ISSUE TITLE
im871a not detected on WSL

### ISSUE THREAD

**Issue by kongo09** [wmbusmeters/wmbusmeters#881]
I have an iM871A-USB device plugged into Windows 11.

Using the description here: https://learn.microsoft.com/en-us/windows/wsl/connect-usb I have attached it to the Ubuntu WSL:

![image](https://user-images.githubusercontent.com/640121/221125555-f6f6f44d-37e7-455b-8231-e495102be352.png)

It's visible in the WSL:

![image](https://user-images.githubusercontent.com/640121/221125687-b449ef58-a6a6-47e3-96c1-22f6a99b780c.png)

`wmbusmeters` is compiled directly from the current source without errors. When I try to access the device, it doesn't find it:

![image](https://user-images.githubusercontent.com/640121/221126145-e4106b7b-6442-4b11-b520-e8de041a4a86.png)

What am I missing?

**Comment by BIBOLV** [comment]
Idea crossed my mind to make similar tests, but as I do not have win11 so I have not done that. Keep us posted if you are able to get this setup working, it would be worth to document for other to use if successful.
