### ISSUE TITLE
Value not changing in Techem mkradio4 water meter

### ISSUE THREAD

**Issue by jammedjackal** [wmbusmeters/wmbusmeters#882]
### Type of request

Bug

### HAOS version

9.5

### wmbusmeters version

1.11.0-2

### Your message goes here

I'm struggling to integrate Techem water meters. They are recognized correctly and visible, but there is no change in meted water value since the first read (24h+). I have used plenty of water since then and physical counter on meter changed accordingly, not same values are still transmitted. Additionally, values are presented with only one decimal digit, which is ridiculous as it will require to use 100 liters of water to spot any difference in measurements in Home Assistant. Anticipating questions - yes, I have used those 100 liters and transmitted value haven't changed.

Telegrams are transmitted every 5 minutes, but I'm wondering what's the point to transmit them so frequent if meter doesn't change the value at all.

I have no clue, is it caused by wmbusmeters or the meter itself or is it legitimate and expected behavior. Does anyone have any idea how to get out of this pickle?

I'm attaching below a sample of 4 telegrams transmitted one after another.
telegram=|2E446850370245217072A0_009F2D290A80253F00000A1119160F1615180E1612141617111512121A28233340202015|+0
telegram=|2E446850370245217072A0_009F2D290A80253F00000A1119160F1615180E1612141617111512121A28233340202015|+0
telegram=|2E446850370245217072A0_009F2D290A80253F00000A1119160F1615180E1612141617111512121A28233340202015|+0
telegram=|2E446850370245217072A0_009F2D290A80253F00000A1119160F1615180E1612141617111512121A28233340202015|+0

**Comment by BIBOLV** [comment]
Please check https://github.com/weetmuts/wmbusmeters/issues/707 - similar issue already discussed.
