### ISSUE TITLE
No dme_07 json config file

### ISSUE THREAD

**Issue by djxmax** [wmbusmeters/wmbusmeters#916]
### Type of request

Enhancement

### HAOS version

9.5

### wmbusmeters version

1.12.0

### Your message goes here

I try to add a device with type dme_07, but I have this error 
`[10:46:36] INFO:  Adding meter: WaterMeterDiehl ...
[10:46:36] INFO:   File /config/wmbusmeters/etc/mqtt_discovery/dme_07.json not found.`

So no mqtt device is creates. I verified in directory and no dme_07.json file.
I this an error or does a workarount is existing ?
Thank you

**Comment by BIBOLV** [comment]
If template does not exist, you can create device in HA manually - as in example at the bottom of https://github.com/wmbusmeters/wmbusmeters-wiki/blob/master/HASS.md .
