### ISSUE TITLE
codifica contattore qwater Siemens

### ISSUE THREAD

**Issue by MatteoRigoldi** [wmbusmeters/wmbusmeters#919]
Explain the problem..... 

https://wmbusmeters.org/analyze/49449344016202511807780dff5f350082aB0000610107c113ffff77840200df2c92150200fc225767020000000000feffd6008601d600cc017c010601f0002B01d9002f046d3B08ee23 

Auto driver  : qwater
Best driver  : qwater 
Using driver : qwater
000   : 49 length (73 bytes)
001   : 44 dll-c (from meter SND_NR)
002   : 9344 dll-mfct (QDS)
004   : 01620251 dll-id (51026201)
008   : 18 dll-version
009   : 07 dll-type (Water meter)
010   : 78 tpl-ci-field (EN 13757-3 Application Layer (no tplh))
011   : 0D dif (variable length Instantaneous value)
012   : FF vif (Manufacturer specific)
013   : 5F vife (?)
014  : 35 varlen=53
015 C?  : 00
024   : 13 vif (Volume l)
025  C? : FFFF
027 C!: 77840200 ("due_date_m3":28.477)
068   : 04 dif (32 Bit Integer/Binary Instantaneous value)
069   : 6D vif (Date and time type)
070 C!: 3B08EE23 ("meter_datetime":"2023-03-14 08:59")

{
    "media":"water",
    "meter":"qwater",
    "name":"",
    "id":"51026201",
    "meter_datetime":"2023-03-14 08:59",
    "total_m3":28.477,
    "status":"OK",
    "timestamp":"2023-03-16T15:14:26Z"
}

**Comment by BIBOLV** [comment]
Could you write properly, in full sentences, like - what is problem you are facing and with what you need help?

**Comment by MatteoRigoldi** [comment]
Ciao, abbiamo sottoposto la stringa alla decodifica del sito ma non è andata a buon fine, in pratica il dato di lettura istantanea su questa stringa da 49 (79 byte) la lettura istantanea risulta dopo i due byte FF-FF posti al 25-26 byte, e non al byte successivo all'unità di misura (13=Volume l) come avviene in altre stringhe della stessa casa costruttrice. Chiediamo se è possibile implementare la decodifica di questa stringa.

**Comment by MatteoRigoldi** [comment]
Ciao,
abbiamo sottoposto la stringa alla decodifica del sito ma non è andata a
buon fine, in pratica il dato di lettura istantanea su questa stringa da 49
(79 byte) la lettura istantanea risulta dopo i due byte FF-FF posti al
25-26 byte, e non al byte successivo all'unità di misura (13=Volume l) come
avviene in altre stringhe della stessa casa costruttrice. Chiediamo se è
possibile implementare la decodifica di questa stringa.


Matteo Rigoldi
contabilizzazione del calore
+39 028467416  <+39+028467416>
<https://www.facebook.com/Joule4.0/>
<https://www.linkedin.com/company/joule40/>
<https://www.instagram.com/joule40energiasottocontrollo/>
<https://twitter.com/Joule40>
<https://monitoraggio.joule40.com/>


Il giorno gio 16 mar 2023 alle ore 17:55 BIBO ***@***.***> ha
scritto:
