### ISSUE TITLE
WMBUSMETERS as daemon stop! 

### ISSUE THREAD

**Issue by chrigabr** [wmbusmeters/wmbusmeters#922]
### Type of request

Question

### OS version

Raspberry PI ZERO 2W

### wmbusmeters version

wmbusmeters version: _

### Your message goes here

Hello when I use WMBUSMETERS in command line it works. However, when I start it as a daemon, it stops. Here is the message in /var/log/wmbusmters 

[2023-03-21_10:19:27] Started config rtlwmbus[MyDongleId] listening on t1
[2023-03-21_10:19:27] (rtlwmbus) error: when starting as daemon, wmbusmeters looked for /rtl_sdr and /usr/bin/rtl_sdr, but found neither!

I have  a directory /usr/bin/rtl-sdr..... how can I fix it?
Thanks!

**Comment by chrigabr** [comment]
ls -l /usr/bin/rtl-sdr
total 164
-rw-r--r-- 1 root root   129 Mar 17 18:02 AUTHORS
drwxr-xr-x 5 root root  4096 Mar 17 18:08 build
drwxr-xr-x 3 root root  4096 Mar 17 18:02 cmake
-rw-r--r-- 1 root root  7724 Mar 17 18:02 CMakeLists.txt
-rw-r--r-- 1 root root  3276 Mar 17 18:02 configure.ac
drwxr-xr-x 2 root root  4096 Mar 17 18:02 contrib
-rw-r--r-- 1 root root 17987 Mar 17 18:02 COPYING
drwxr-xr-x 3 root root  4096 Mar 17 18:02 debian
-rw-r--r-- 1 root root 72355 Mar 17 18:02 Doxyfile.in
-rwxr-xr-x 1 root root  5440 Mar 17 18:02 git-version-gen
drwxr-xr-x 2 root root  4096 Mar 17 18:02 include
-rw-r--r-- 1 root root   249 Mar 17 18:02 librtlsdr.pc.in
drwxr-xr-x 2 root root  4096 Mar 17 18:02 m4
-rw-r--r-- 1 root root  1124 Mar 17 18:02 Makefile.am
-rw-r--r-- 1 root root   212 Mar 17 18:02 README
-rw-r--r-- 1 root root  7642 Mar 17 18:02 rtl-sdr.rules
drwxr-xr-x 4 root root  4096 Mar 17 18:02 src


ls -l /usr/bin/rtl-wmbus
total 332
-rwxr-xr-x 1 root root    476 Mar 17 19:19 androidbuild.bat
-rw-r--r-- 1 root root   1562 Mar 17 19:19 atan2.h
drwxr-xr-x 2 root root   4096 Mar 17 21:40 build
-rwxr-xr-x 1 root root     23 Mar 17 19:19 build-deb.sh
drwxr-xr-x 4 root root   4096 Mar 17 19:19 debian
drwxr-xr-x 2 root root   4096 Mar 17 19:19 filter
-rw-r--r-- 1 root root   3291 Mar 17 19:19 fir.h
-rw-r--r-- 1 root root   2377 Mar 17 19:19 iir.h
drwxr-xr-x 3 root root   4096 Mar 17 19:19 include
-rw-r--r-- 1 root root   2199 Mar 17 19:19 Makefile
-rw-r--r-- 1 root root   2260 Mar 17 19:19 moving_average_filter.h
-rw-r--r-- 1 root root    983 Mar 17 19:19 net_support.h
drwxr-xr-x 2 root root   4096 Mar 17 19:19 pics
-rw-r--r-- 1 root root   3295 Mar 17 19:19 ppf.h
-rw-r--r-- 1 root root   9280 Mar 17 19:19 README.md
-rw-r--r-- 1 root root 174065 Mar 17 19:19 readme.pdf
-rw-r--r-- 1 root root  45638 Mar 17 19:19 rtl_wmbus.c
-rwxr-xr-x 1 root root   2162 Mar 17 19:19 rtl_wmbus.py
-rw-r--r-- 1 root root   9460 Mar 17 19:19 s1_packet_decoder.h
drwxr-xr-x 2 root root   4096 Mar 17 19:19 samples
-rw-r--r-- 1 root root  24163 Mar 17 19:19 t1_c1_packet_decoder.h

**Comment by pswiatki** [comment]
Exactly. This is incorrect.

**Comment by chrigabr** [comment]
Hello, I'm sorry I didn't understand what I have to do... can you tell me a little more please :-) ?
Many thanks !!!

**Comment by weetmuts** [comment]
You need to do the same fix I told you about here:

https://github.com/wmbusmeters/wmbusmeters/issues/921#issuecomment-1474856707

but for these two commands. :-)

**Comment by chrigabr** [comment]
OK It Works :-)

Thanks for all!
