### ISSUE TITLE
Strange LSE messages, CI 0xA0, 0xA2, 0xA4

### ISSUE THREAD

**Issue by micw** [wmbusmeters/wmbusmeters#930]
### Type of request

New device support

### Meter description

Hello,

I'm often seeing "Garbage" with LSE as manufacturer in the field, especially if there are Qundis repeaters. Below are some examples. The characteristics are
* "Serial" field often contains characters
* "Type" field changes from message to message
* CI field is one of 0xA0, 0xA2, 0xA4

Do you have any idea how to decode the message?

My guess is that the repeater wraps the original message in a proprietary format.

I also think there is an issue in wmbusmeters decoding the message below starting with 0x8F. With my own decoder, I get:

![grafik](https://user-images.githubusercontent.com/186753/228135640-2918a409-a7fc-408f-b59f-6ac772eeeeec.png)

### Logged telegrams from meter in decrypted format

```shell
43C465B251D0800AF088A0830600533AE70131446532881200772C087AD7000000046D1D15FB230B6E420400426CDE294B6E890200326CFFFF82046CFC228B046E910300

8FC465B251D05000E01FA465B248631111FE31350003FF0F5F33011C0F221D98489C2BA0020000446532251300772C087A67000000046D2E07E9230B6E380000426CDE294B6E280300326CFFFF5F410118FFFFFC2201398B046E360000280000210000000000000000280300280300280300280300280300280300860200360200600100970000390000000000680200
```

**Comment by weetmuts** [comment]
Interesting a good telegam is hidden inside the big telegram.
Perhaps the Qundis repeater is an old style non-standardized repeater?

Decoding your first telegram looks like this:
https://wmbusmeters.org/analyze/43c465B251d0800af088a0830600533ae70131446532881200772c087ad7000000046d1d15fB230B6e420400426cde294B6e890200326cffff82046cfc228B046e910300

Which looks fine, ci-field  0xA0, 0xA2, 0xA4 are defined as manufacturer specific according to the standard.

And inside this telegram there is a proper telegram:
https://wmbusmeters.org/analyze/31446532881200772C087AD7000000046D1D15FB230B6E420400426CDE294B6E890200326CFFFF82046CFC228B046E910300





https://wmbusmeters.org/analyze/31446532881200772C087AD7000000046D1D15FB230B6E420400426CDE294B6E890200326CFFFF82046CFC228B046E910300
