### ISSUE TITLE
Unknown state i HA

### ISSUE THREAD

**Issue by PalleLofter** [wmbusmeters/wmbusmeters#940]
### Type of request

Enhancement

### OS version

2023.4.2

### wmbusmeters version

1.12.0

### Your message goes here

Hello

I´m from Denmark and i used WMbusmeters to  receive telegrams from Mulitcal21 (MC21) and Mulitcal403 (MC403), and this works perfect from October til December 2022. 
Since december i not receive any data on my HA dashboard from MC403 for this four sensor:
- MC403 T1 temp.
- MC403 T2 temp.
- MC403 total energy
- MC403 volume flow 
All four is unknown. 
In MC403 i get low battery - "normal" and MC403 total volume 1.035,7m3. So i think signal and telegrams work through mqtt and in HA. 

I have use mqtt explorer to check telegrams is send correct in to HA.
![image](https://user-images.githubusercontent.com/130384197/230934494-a772f686-2789-4a6a-ab75-5c1af69eb77f.png)

I see MC403 telegrams works  in logs - no fault, and i see telegrams in HA.

I think this problem is en HA, but i dont know where i have t ofix this problem. In MC403 debug (mqtt information) i see this.
![image](https://user-images.githubusercontent.com/130384197/230935747-732ac359-4c12-40b5-a534-6c566831ba03.png)

I have try to restart WMbusmeter, reinstall, and reinstall Mqtt - nothin works.

In HA under developertool in condition i see this: 
![image](https://user-images.githubusercontent.com/130384197/230937181-df64bc5f-017d-4d15-a1c2-1916364b186b.png)
if I enter a value instead of unknown, this will remain until the sensor updates a new value, then it will change back to unknown.

I don't understand the problem and can't see what I'm missing

**Comment by BIBOLV** [comment]
Hi,
When you reinstalled HA, did you restore config and all history? 
Did you compare also received telegrams from both meters and how they show up in HA?
Have you tried to remove device that does not show up correctly from HA?
