### ISSUE TITLE
uninstall.sh removes all configuration without any additional parameter

### ISSUE THREAD

**Issue by travnick** [wmbusmeters/wmbusmeters#941]
### Type of request

Bug

### OS version

any linux

### wmbusmeters version

1.12

### Your message goes here

As far as I see, every linux package manager does not remove any configuration files of uninstalled software without additional parameter (e.g. `--purge` of `apt`). Others are about to add suffix `.new`, `.old` so one is able to compare and decide.

It's kind of surprise that my config files didn't survive reinstallation of `wmbusmetters`.
I'm considering it as a bug to remove configuration without any additional parameter passed to `uninstall.sh`.

**Comment by weetmuts** [comment]
Yes, your are right. The uninstall script has not been the focus of attention for a very long time.
I have pushed a fix where "make uninstall" does not remove config files and the wmbusmeters user/group.
"make uninstall_purge" will remove the config files and the wmbusmeters user/group.
