### ISSUE TITLE
(apator162) telegram contains a register (97) with unknown size.

### ISSUE THREAD

**Issue by niklas007** [wmbusmeters/wmbusmeters#946]
### Type of request

Bug

### HAOS version

Home Assistant 2023.4.4 Supervisor 2023.04.0 Operating System 9.5 Frontend 20230411.1 - latest

### wmbusmeters version

Current version: 0.2.20

### Your message goes here

6E4401069240590205077A730060852F2F0FC491349718020043E204848073B6587ECC04040000101FB702007B0112A70200488B0200AA730200545602003C380200891D0200660002006AE201005BC30100B3940100C66F0100A8500100A0038CE003FFFFFFFFFFFFFFFFFFFFD730
(apator162) telegram contains a register (97) with unknown size.

somethings is wrong no readings in a long time

**Comment by weetmuts** [comment]
Ah, you are running an old version of wmbusmeters in your ha-addon. The latest version has a fix. :-) Please test!
