### ISSUE TITLE
Help with getting the device encryption key

### ISSUE THREAD

**Issue by sanchosk** [wmbusmeters/wmbusmeters#952]
I would like to find out how can I get the encryption key for the Topas ES KR.
The message arrives, I am using the correct driver, but it seems to be encrypted and I cannot get the data out.
Any suggestions for newbie on how to get the key?
I doubt I'll be able to get it from local water company...

**Comment by BIBOLV** [comment]
Getting key is only option - please check [this](https://github.com/wmbusmeters/wmbusmeters/issues/446) .

**Comment by SaSa1983** [comment]
There's no chance that the developer cab help you to get the required key.
In my case I got mine by sending a request to the local city.

**Comment by sanchosk** [comment]
Actually, the developer did offered a key that worked :)

On May 8, 2023 5:33:55 PM GMT+02:00, Sascha Sander ***@***.***> wrote:
>There's no chance that the developer cab help you to get the required key.
>In my case I got mine by sending a request to the local city. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wmbusmeters/wmbusmeters/issues/952#issuecomment-1538587171
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Sent from /e/ Mail.
