### ISSUE TITLE
Add logrotate and supercronic to docker file

### ISSUE THREAD

**Issue by jens62** [wmbusmeters/wmbusmeters#964]
### Type of request

Enhancement

### OS version

QTS 5.0.1.2376 (QNAP NAS)

### wmbusmeters version

1.12.0-16

### Your message goes here

Please take a look at [https://github.com/wmbusmeters/wmbusmeters/issues/960#issuecomment-1554001198](https://github.com/wmbusmeters/wmbusmeters/issues/960#issuecomment-1554001198) and consider to enhance the wmbusmeters docker file accordingly.

**Comment by BIBOLV** [comment]
Closing as duplicate of https://github.com/wmbusmeters/wmbusmeters/issues/960
