### ISSUE TITLE
Positive RSSI dBm value?

### ISSUE THREAD

**Issue by mathzol** [wmbusmeters/wmbusmeters#975]
### Type of request

Question

### OS version

Linux

### wmbusmeters version

1.13.1

### Your message goes here

I use RTL-SDR dongle and just saw that rssi value is positive, which is not possible I think. 

`{"media":"heat","meter":"sharky774","name":"HeatMeter","id":"123456","total_energy_consumption_kwh":11,"total_volume_m3":0.859,"volume_flow_m3h":0,"power_kw":0,"flow_temperature_c":26.8,"return_temperature_c":26.6,"operating_time_in_error_h":0,"energy_at_set_date_kwh":11,"set_date":"2023-05-31","timestamp":"2023-06-06T21:22:42Z","device":"rtlwmbus[00000001]","rssi_dbm":153}`

What could be wrong?

**Comment by weetmuts** [comment]
A proper absolute rssi value cannot be calculated for the rtlsdr dongles because of the autogain. It can be used to compare with identical rtl sdr dongles in the same setting though.

Another solution would be to have a different name/unit of this relative value.

**Comment by weetmuts** [comment]
So it is probably better that the value is positive and clearly not a normal rssi value, than tricking users into believing it is a proper absolute rssi value. :-)

**Comment by mathzol** [comment]
So if the gain handled by manualy it turned to possible to calcule? 
Are there any debug method for read out RSSI value, to know how good is the receiving?

**Comment by pswiatki** [comment]
The higher the value in `rssi_dbm` the better. 153 in your example above seems excellent.

**Comment by mathzol** [comment]
@pswiatki thank you, I used a tuned and untuned stock antenna too, but the difference was so little, maybe rtlsdr compensate with autogain, I dont know, but its stable for me too.
