### ISSUE TITLE
ISTA meter P/N: 19320 radio 3 net

### ISSUE THREAD

**Issue by dimabors** [wmbusmeters/wmbusmeters#992]
### Type of request

New device support

### Meter description

Hi there,
I have checked [this ](https://github.com/wmbusmeters/wmbusmeters/issues/436) issue but it does not answer my question much. 
I have several meters from Kamstrup, Gavazzi those work fine. Also, I have an ISTA water meter that is not able to decrypt it. I have got the encryption key from the utility company and when I am trying to decrypt the telegram I get this error. 

```
(meter) MyCounter: meter detection could not find driver for id: 10685115 mfct: (IST) Ista (0x2674) type: Water meter (0x07) ver: 0x29
(meter) please consider opening an issue at https://github.com/wmbusmeters/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
(meter) newly created meter (MyCounter 10685115 auto) did not handle telegram!
```
The utility company has confirmed that is using an OMS standard for these meters
Also, I have tried to decrypt it on [https://wmbusmeters.org/](https://wmbusmeters.org/ ) but it did not work by having the following error 
`036 CE: 0792D838D08624E28E1D7A0DC5E92CF1DCFD2272554C8838BC350F662E9F79105093EEF2F10B2981696E9F0BF834F8649A encrypted mac failed`

Could you please help me with the following problem? 

### Logged telegrams from meter in decrypted format

```shell
IST	10685115	Water	54 44 74 26 15 51 68 10 29 07 8C 20 21 90 0F 00 2C 25 B4 A5 1F B3 4E DB 77 DA E4 61 FB 92 7A 44 00 30 07 10 86 01 51 84 1C 74 74 7F F0 6F 07 1C EF 8E 26 79 B8 A1 1F 59 F0 5E 07 26 D3 27 3C 7D A1 8D 30 5E BE C9 1B 42 45 92 C3 94 2A D0 7D C4 37 E2 9B 80 A7 03 01 FD 8E 6E
IST	10685115	Water	54 44 74 26 15 51 68 10 29 07 8C 20 22 90 0F 00 2C 25 B5 A5 1F B3 77 16 37 31 EC 81 79 86 7A 45 00 30 07 10 79 A8 A7 8A 47 7A 8D 5C 69 10 41 DC A8 17 87 30 7B 2F 5B 89 1C 6C 0F 4D B9 00 D8 F8 4C 2A 76 6C D1 C4 1B 6F 88 FB E6 9A C1 18 E4 E1 6A 34 C3 42 AA 03 01 FB 4F D2
IST	10685115	Water	54 44 74 26 15 51 68 10 29 07 8C 20 23 90 0F 00 2C 25 B6 A5 1F B3 B5 91 BC A4 84 F6 F3 8F 7A 46 00 30 07 10 5E 1C 8F 68 CC 49 F6 FB 3E 54 0A 9E 50 A8 7E 84 9C 55 9E EF 9E CF 6C F7 10 22 57 95 AC E3 BC DB 94 56 9C 98 D2 E9 47 2F 27 EE B7 D9 F8 63 26 2B A9 03 01 F8 8D 3A


And this is the key:
95412095D10C746F1E3A145D3009D38A
```

​✅​**Answer**​

Consider only the first 0x54 (84 bytes). My sniffer was adding bytes at the end of the original telegram that was sent by the meter. 

The correct telegram:

```
544474261551681029078c2022900f002c25B5a51fB377163731ec8179867a450030071079a8a78a477a8d5c691041dca81787307B2f5B891c6c0f4dB900d8f84c2a766cd1c41B6f88fBe69ac118e4e16a34c342

Enc key: 95412095D10C746F1E3A145D3009D38A
```

**Comment by BenRoe** [comment]
Is there any progress on this topic?
Have the same water meter and would like to capture the data and import it to may Home Assistant.

**Comment by itcsoft54** [comment]
hello @dimabors, 
Can you post here the wmbusmeters command you used to get you used to show your ista watermeter ?

**Comment by dimabors** [comment]
@itcsoft54 
The sniffer that I used was adding 10 bytes at the end of the telegram + RSSI. That was the problem in my case. 
I created a script that takes only the bytes that the meters sends. So, first byte (`0x54`) is the length of the telegram, considering the first 84 bytes in our case including `byte[0]`. After the `byte[83]` everything is dropped.

**Comment by lukaszswitaj** [comment]
@dimabors Be so kind and give us more details please:
1. what receiver/sniffer are you using?
2. can you quote the contents of the command or configuration file you used to receive the telegrams?

This water meter is a real pain in the ass for the community, there are many indications that your achievements could be a breakthrough for us :)

**Comment by dimabors** [comment]
> @dimabors Be so kind and give us more details please:
> 
> 1. what receiver/sniffer are you using?
> 2. can you tell us the contents of the command or configuration file you used to receive the telegrams?
> 3. how you get the counter id and encryption key?
> 
> This water meter is a real pain in the ass for the community, there are many indications that your achievements could be a breakthrough for us :)

@lukaszswitaj 
1. The chip that I am using is RC1180-mbus3 with a standard configuration with RSSI Enabled. 
2. I am analyzing the raw telegram directly, not filtering it. The only change is the WMBUS Chip adds the RSSI at the end of the telegram. 
3. I am following the WMBUS documentation [OMS-Spec_Vol2_Primary_v402.pdf](https://github.com/wmbusmeters/wmbusmeters/files/14383591/OMS-Spec_Vol2_Primary_v402.pdf), and [OMS-Spec_Vol2_Primary_v421.pdf](https://github.com/wmbusmeters/wmbusmeters/files/14383594/OMS-Spec_Vol2_Primary_v421.pdf). 
    This meter that I have has the AES-CMAC type or mode 7 (see the byte below)
544474261551681029078c2022900f002c25B5a51fB377163731ec8179867a450030`07`1079a8a78a477a8d5c691041dca81787307B2f5B891c6c0f4dB900d8f84c2a766cd1c41B6f88fBe69ac118e4e16a34c342
   You have to generate a new key by using AES-CMAC every single time when the meter sends a new telegram, and then with that new key, you have to decrypt by using AES-CBC.
In steps:
1. Gateway receives the telegram
2. Derive the key: K = CMAC( MK , D || C || ID || 07h || 07h || 07h || 07h || 07h || 07h || 07h )
- MK is individual master key (according to 9.2.4.2)
- D is Derivation constant (according to 9.2.4.3)
- C is message counter CM, C’M, C’’M, CGW or C’GW (according to 9.2.4.4)
- ID is Meter ID (according to 9.2.4.5)
- 0x07 To fill in the the rest
4. Use AES-CMAC to generate the new key
5. Use AES-CBC to decrypt the telegram
6. Follow the 13757-3 standard for the data.

**Comment by itcsoft54** [comment]
@dimabors thx a lot.
Did you send something to your meter to get telegram ? Maybe you know which mode is used by your meter. I try to capture my ista meter but I never get any telegram from it.

**Comment by XLDom** [comment]
Hello, thx for the work,
I have an ista meter. I don't understand everything that is described in this issue: If we need to do something ourselves, or if it will be implemented in git with pull request ?

**Comment by itcsoft54** [comment]
@weetmuts plz add label to disable auto close of this issue

**Comment by BinaryBrain86** [comment]
Hi @dimabors, was this activity resulting in any pull request or code update to support the ISTA  meter with the radio net 3?

I believe strongly this will have a great benefit for the community, since the meters are used pretty often. And as @lukaszswitaj said, this meter are a pain in the ass.

**Comment by dimabors** [comment]
No need for that as this specific meter is already supported.
[Check here](https://wmbusmeters.org/analyze/544474261551681029078c2022900f002c25B5a51fB377163731ec8179867a450030071079a8a78a477a8d5c691041dca81787307B2f5B891c6c0f4dB900d8f84c2a766cd1c41B6f88fBe69ac118e4e16a34c342:evo868:95412095D10C746F1E3A145D3009D38A) 
It's not supported if there is an ISTA DataLogger that transmits mbus

**Comment by BinaryBrain86** [comment]
@dimabors, do you actually mean this one (optosonic u 3 radio net)? 

![Image](https://github.com/user-attachments/assets/55610300-0cc3-4c16-a507-a0dae988b462)

Connected with this one (Ista ultego 3 smart)?

![Image](https://github.com/user-attachments/assets/016b0d5b-0b68-498c-b53d-b711e0f82075)

**Comment by chris299** [comment]
> No need for that [@BinaryBrain86](https://github.com/BinaryBrain86) as this specific meter is already supported. [Check here](https://wmbusmeters.org/analyze/544474261551681029078c2022900f002c25B5a51fB377163731ec8179867a450030071079a8a78a477a8d5c691041dca81787307B2f5B891c6c0f4dB900d8f84c2a766cd1c41B6f88fBe69ac118e4e16a34c342:evo868:95412095D10C746F1E3A145D3009D38A) It's not supported if there is an ISTA DataLogger that transmits mbus
> 

@dimabors thank you for your insights. just to make clear, can you confirm, that the ISTA devices need to be explicitly configured to use either wmbus-mode (OMS-C1) or a special protocol ("ISTA-Funk")? the data sheet is not clear on this. it looks to me as if it sends both protocols simultaniously https://oms-group.org/wp-content/uploads/2025/03/C.83.0071_Technisches-Datenblatt_doprimo-3-radio-net-3-OMS_DE.pdf
