### ISSUE TITLE
docker bash: wmbusmeters: command not found

### ISSUE THREAD

**Issue by jonas240** [wmbusmeters/wmbusmeters#995]
### Type of request

Question

### OS version

HomeAssistant OS 10.3 (RasperryPi4)

### wmbusmeters version

1.14.0

### Your message goes here

Hi,
I tried to use the command 'wmbusmeters 32446850399721226980A0019F2D310FF02E1E036B0971090100010002' in the command line of the docker container (using the portainer add on) of the ha-add-on to decode a telegram I received. But that returned 'wmbusmeters: command not found'.

How can I decode a telegram using the command line when using the ha-addon

In addition, I tried to use the docker container on my pc. There, as well, I am unable to use the 'wmbusmeters' command.

I greatly appreciate your help.

**Comment by BIBOLV** [comment]
Hi,
Try `/wmbusmeters/wmbusmeters --analyze 32446850399721226980A0019F2D310FF02E1E036B0971090100010002`

**Comment by jonas240** [comment]
Thanks that solved it
