### ISSUE TITLE
Plex Pulling no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by smiller0924** [wmbusmeters/wmbusmeters#997]
### Type of request

Question

### OS version

Open Media Vault 6

### wmbusmeters version

n/a

### Your message goes here

Installing Plex in Docker Container on OMV 6 - RPI 3B+.  Getting the following error:

![image](https://github.com/wmbusmeters/wmbusmeters/assets/108164566/7cc8dd32-3a9d-4f63-af92-88beb07bb0a7)

Saw a similar post that there needed to be a modification to the OMV Docker Container to make it ignore the 'manifest for linux/arm/v7 in the manifest list entries'.  How do I go about resolving this?

**Comment by weetmuts** [comment]
It seems like you opened an issue in the wrong github project.
